#pragma once
/********************************************************************
//	Created:	2019/12/18   9:55
//	Filename: 	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_RfcComponents\RfcComponents_HttpServer\HttpServer_Error.h
//	File Path:	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_RfcComponents\RfcComponents_HttpServer
//	File Base:	HttpServer_Error
//	File Ext:	h
//  Project:    NetEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	HTTP服务导出错误码
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                        导出的简单HTTP服务错误
//////////////////////////////////////////////////////////////////////////
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETCLIENT_PARAMENT 0x121A0000     //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETCLIENT_EMPTY 0x121A0001        //没有客户端可以获取包
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETCLIENT_NOTFOUND 0x121A0002     //没有可以处理的包
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETCLIENT_SIZE 0x121A0003         //提供的缓冲区大小不够
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETCLIENT_NOTDATA 0x121A0004      //此客户端没有数据
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETCLIENT_HDRCOMPLATE 0x121A0005  //HTTP头还没组包完成
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETCLIENT_BODYCOMPLATE 0x121A0006 //组包还没完成
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PARSE_PARAMENT 0x121A0010         //解析参数失败
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PARSE_NOHTTPHDR 0x121A0011        //没有HTTP头，或者HTTP不标准，无法继续
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PARSE_NOTMETHOD 0x121A0012        //没有方法名
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PARSE_NOTURL 0x121A0013           //没有URI地址
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PARSE_NOTVER 0x121A0014           //没有HTTP版本号
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_SENDMSG_PARAMENT 0x121A0020       //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_INSERT_PARAMENT 0x121A0030        //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_INSERT_NOTFOUND 0x121A0031        //没有找到
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PUSH_NOTHTTP 0x121A0040           //不是HTTP标准协议
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PUSH_MALLOCHDR 0x121A0041         //申请临时HTTP头内存失败
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PUSH_MALLOCLIST 0x121A0042        //申请HTTP头字段内存失败
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_PUSH_MALLOCBODY 0x121A0043        //申请HTTP数据内存失败
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_CLOSE_PARAMENT 0x121A0050         //关闭客户端失败，参数错误
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_CLOSE_NOTFOUND 0x121A0051         //关闭客户端失败，没有找到
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_SENDMSG_LEN 0x121A0060            //发送失败，提供的缓冲区大小不够
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETRANDOM_PARAMENT 0x121A0070     //参数错误，获取失败
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETRANDOM_EMPTY 0x121A0071        //没有任何可用队列
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETLIST_PARAMENT 0x121A0080       //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETLIST_EMPTY 0x121A0081          //为空
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_CREATE_PARAMENT 0x121A0090        //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_CREATE_MALLOC 0x121A0091          //申请内存失败
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_CREATE_NOTPOOL 0x121A0092         //没有找到可用分布池
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETPOOL_PARAMENT 0x121A00A0       //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_GETPOOL_NOTENABLE 0x121A00A1      //没有启用
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_ETPOOL_NOTFOUND 0x121A00A2        //没有找到
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_WAITEVENT_NOTFOUND 0x121A00B0     //没有找到
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_WAITEVENT_NOPACKET 0x121A00B1     //没有数据包了
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_ACTIVEEVENT_NOTFOUND 0x121A00C0   //没有找到
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_EX_MALLOC 0x121A0100              //申请内存失败
#define ERROR_RFCCOMPONENTS_HTTP_SERVER_EX_NOTFOUND 0x121A0101            //没有找到
//////////////////////////////////////////////////////////////////////////
//                        导出的HTTP帮助处理函数错误
//////////////////////////////////////////////////////////////////////////
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETFILED_PARAMENT 0x121A1000        //获取字段内容失败，参数错误
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETFILED_NOTFOUND 0x121A1001        //没有找到指定的字段
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETURLAPI_PARAMENT 0x121A1010       //获取失败，参数错误
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETURLAPI_NOTTYPE 0x121A1011        //没有找到API类型
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETURLAPI_NOTNAME 0x121A1012        //没有找到API名称
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETURLAPI_NOTVER 0x121A1013         //没有找到API版本
#define ERROR_RFCCOMPONENTS_HTTP_HELP_REGPROCESS_PARAMENT 0x121A1020      //注册处理程序失败，参数错误
#define ERROR_RFCCOMPONENTS_HTTP_HELP_REGPROCESS_EXIST 0x121A1021         //注册处理程序失败，这个处理程序名称已经存在
#define ERROR_RFCCOMPONENTS_HTTP_HELP_CANCPROCESS_PARAMENT 0x121A1030     //注销处理程序失败，参数错误
#define ERROR_RFCCOMPONENTS_HTTP_HELP_HDPROCESS_PARAMENT 0x121A1040       //参数错误，处理失败
#define ERROR_RFCCOMPONENTS_HTTP_HELP_HDPROCESS_NOTEXIST 0x121A1041       //不存在的处理程序
#define ERROR_RFCCOMPONENTS_HTTP_HELP_HDPROCESS_EXEC 0x121A1042           //执行失败，可能不是一个标准的注册程序
#define ERROR_RFCCOMPONENTS_HTTP_HELP_HDPROCESS_HTTPCODE 0x121A1043       //获取HTTP状态码失败
#define ERROR_RFCCOMPONENTS_HTTP_HELP_HDPROCESS_MINITYPE 0x121A1044       //获取返回类型失败
#define ERROR_RFCCOMPONENTS_HTTP_HELP_HDPROCESS_LEN 0x121A1045            //获取长度失败
#define ERROR_RFCCOMPONENTS_HTTP_HELP_HDPROCESS_MSG 0x121A1046            //获取返回内容失败
#define ERROR_RFCCOMPONENTS_HTTP_HELP_EXECGI_PARAMENT 0x121A1050          //执行CGI程序失败,参数错误
#define ERROR_RFCCOMPONENTS_HTTP_HELP_EXECGI_NOTDATA 0x121A1051           //CGI程序执行完毕,但是没有任何数据返回
#define ERROR_RFCCOMPONENTS_HTTP_HELP_EXECGI_TITLE 0x121A1052             //解析CGI标题失败,可能不是标准的CGI程序
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETAUTH_PARAMENT 0x121A1060         //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETAUTH_BUFFER 0x121A1061           //缓冲区错误,不是标准的密码区
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETAUTH_USER 0x121A1062             //没有取到用户名
#define ERROR_RFCCOMPONENTS_HTTP_HELP_GETAUTH_NOTSUPPORT 0x121A1063       //不支持的验证类型
//////////////////////////////////////////////////////////////////////////
//                        导出的HTTP配置文件管理器错误
//////////////////////////////////////////////////////////////////////////
#define ERROR_RFCCOMPONENTS_HTTP_CONFIG_INITCODE_NOTFOUND 0x121A2000      //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_CONFIG_INITCODE_PARSE 0x121A2001         //解析错误
#define ERROR_RFCCOMPONENTS_HTTP_CONFIG_INITCODE_OPENFILE 0x121A2002      //打开文件失败
#define ERROR_RFCCOMPONENTS_HTTP_CONFIG_GETCODE_PARAMENT 0x121A2010       //参数错误
#define ERROR_RFCCOMPONENTS_HTTP_CONFIG_GETCODE_NOTFOUND 0x121A2011       //没有找到
#define ERROR_RFCCOMPONENTS_HTTP_CONFIG_INITMIME_PARAMENT 0x121A2020      //参数错误，初始化失败
#define ERROR_RFCCOMPONENTS_HTTP_CONFIG_INITMIME_READFILE 0x121A2021      //读取配置文件错误
#define ERROR_RFCCOMPONENTS_HTTP_CONFIG_GETMIME_PARAMENT 0x121A2030       //参数错误
