#pragma once
/********************************************************************
//	Created:	2019/12/23   15:41
//	Filename: 	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_RfcComponents\RfcComponents_SDPProtocol\SDPProtocol_Error.h
//	File Path:	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_RfcComponents\RfcComponents_SDPProtocol
//	File Base:	SDPProtocol_Error
//	File Ext:	h
//  Project:    NetEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	SDP错误信息导出
//	History:
*********************************************************************/
/************************************************************************/
/*                     SDP打包器导出错误                                */
/************************************************************************/
#define ERROR_RFCCOMPONENTS_SDP_PACKET_CREATE_PARAMENT 0x70E0000         //创建失败,参数错误
#define ERROR_RFCCOMPONENTS_SDP_PACKET_GETPACKET_PARAMENT 0x70E0010      //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PACKET_GETPACKET_NOTFOUND 0x70E0011      //没有找到指定SDP会话
#define ERROR_RFCCOMPONENTS_SDP_PACKET_GETPACKET_MUSTBE 0x70E0012        //必备条件为满足
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OWNER_PARAMENT 0x70E0020          //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OWNER_NOTFOUND 0x70E0021          //没有找到句柄
#define ERROR_RFCCOMPONENTS_SDP_PACKET_SESSION_PARAMENT 0x70E0030        //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PACKET_SESSION_NOTFOUND 0x70E0031        //客户端句柄没有找到
#define ERROR_RFCCOMPONENTS_SDP_PACKET_KEEPTIME_NOTFOUND 0x70E0040       //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PACKET_ADDMEDIA_PARAMENT 0x70E0050       //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PACKET_ADDMEDIA_NOTFOUND 0x70E0051       //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PACKET_ATTRAUDIO_PARAMENT 0x70E0060      //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PACKET_ATTRAUDIO_NOTFOUND 0x70E0061      //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PACKET_ATTRVIDEO_PARAMENT 0x70E0070      //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PACKET_ATTRVIDEO_NOTFOUND 0x70E0071      //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OPTNAME_PARAMENT 0x70E0080
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OPTNAME_NOTFOUND 0x70E0081
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OPTCONTACT_PARAMENT 0x70E0090
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OPTCONTACT_NOTFOUND 0x70E0091
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OPTBAND_NOTFOUND 0x70E00A0
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OPTRANGE_NOTFOUND 0x70E00B0
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OPTADDATTR_PARAMENT 0x70E00C0
#define ERROR_RFCCOMPONENTS_SDP_PACKET_OPTADDATTR_NOTFOUND 0x70E00C1
/************************************************************************/
/*                     SDP解析器导出错误                                */
/************************************************************************/
#define ERROR_RFCCOMPONENTS_SDP_PARSE_CREATE_PARAMENT 0x70E1001          //创建失败,参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_VERSION_PARAMENT 0x70E1010         //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_VERSION_NOTFOUND 0x70E1011         //没有找到客户端
#define ERROR_RFCCOMPONENTS_SDP_PARSE_VERSION_FAILED 0x70E1012           //没有找到版本号
#define ERROR_RFCCOMPONENTS_SDP_PARSE_OWNER_PARAMENT 0x70E1020           //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_OWNER_NOTFOUND 0x70E1021           //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PARSE_OWNER_PROTO 0x70E1022              //协议错误,不完整
#define ERROR_RFCCOMPONENTS_SDP_PARSE_OWNER_FAILED 0x70E1023             //没有找到OWNER协议
#define ERROR_RFCCOMPONENTS_SDP_PARSE_CONNECT_PARAMENT 0x70E1030         //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_CONNECT_NOTFOUND 0x70E1031         //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PARSE_CONNECT_PROTO 0x70E1032            //协议错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_CONNECT_FAILED 0x70E1033           //没有找到此协议字段
#define ERROR_RFCCOMPONENTS_SDP_PARSE_SESSION_PARAMENT 0x70E1040         //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_SESSION_NOTFOUND 0x70E1041         //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PARSE_SESSION_FAILED 0x70E1042           //协议字段不存在
#define ERROR_RFCCOMPONENTS_SDP_PARSE_TIME_PARAMENT 0x70E1050            //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_TIME_NOTFOUND 0x70E1051            //没有找到客户端
#define ERROR_RFCCOMPONENTS_SDP_PARSE_TIME_PROTO 0x70E1052               //协议字段不存在
#define ERROR_RFCCOMPONENTS_SDP_PARSE_TIME_FAILED 0x70E1053              //协议字段不存在
#define ERROR_RFCCOMPONENTS_SDP_PARSE_GETVIDEO_PARAMENT 0x70E1060        //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_GETVIDEO_NOTFOUND 0x70E1061        //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PARSE_GETVIDEO_PROTO 0x70E1062           //协议错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_GETVIDEO_FAILED 0x70E1063          //此协议字段不存在
#define ERROR_RFCCOMPONENTS_SDP_PARSE_GETAUDIO_PARAMENT 0x70E1070        //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_GETAUDIO_NOTFOUND 0x70E1071        //没有找到句柄
#define ERROR_RFCCOMPONENTS_SDP_PARSE_GETAUDIO_PROTO 0x70E1072           //协议不正确
#define ERROR_RFCCOMPONENTS_SDP_PARSE_GETAUDIO_FAILED 0x70E1073          //协议字段不存在
#define ERROR_RFCCOMPONENTS_SDP_PARSE_MEDIANAME_PARAMENT 0x70E1080       //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_MEDIANAME_NOTFOUND 0x70E1081       //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PARSE_MEDIANAME_FAILED 0x70E1082         //没有这个协议字段
#define ERROR_RFCCOMPONENTS_SDP_PARSE_CONTACT_PARAMENT 0x70E1090         //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_CONTACT_NOTFOUND 0x70E1091         //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PARSE_CONTACT_FAILED 0x70E1092           //没有这个协议字段
#define ERROR_RFCCOMPONENTS_SDP_PARSE_BANDWIDTH_PARAMENT 0x70E10A0       //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_BANDWIDTH_NOTFOUND 0x70E10A1       //没有找到
#define ERROR_RFCCOMPONENTS_SDP_PARSE_BANDWIDTH_FAILED 0x70E10A2         //协议字段不存在
#define ERROR_RFCCOMPONENTS_SDP_PARSE_ATTR_PARAMENT 0x70E10B0            //参数错误
#define ERROR_RFCCOMPONENTS_SDP_PARSE_ATTR_NOTFOUND 0x70E10B1            //没有找到句柄
#define ERROR_RFCCOMPONENTS_SDP_PARSE_ATTR_FAILED 0x70E10B2              //没有找到属性字段
