#pragma once
/********************************************************************
//	Created:	2020/08/31  16:41:12
//	File Name: 	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_RfcComponents\RfcComponents_UPnpProtocol\UPnpProtocol_Error.h
//	File Path:	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_RfcComponents\RfcComponents_UPnpProtocol
//	File Base:	UPnpProtocol_Error
//	File Ext:	h
//  Project:    XEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	UPNP协议导出错误
//	History:
*********************************************************************/
/*************************************************************************
                       UPNP客户端导出错误
*************************************************************************/
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_CREATE_PARAMENT 0x120F0001      //参数错误
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_CREATE_MALLOC 0x120F0002        //申请内存失败
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_SEARCH_NOTFOUND 0x120F0010      //获取状态信息错误
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_SEARCH_EMPTY 0x120F0011         //搜索失败,没有找到可用设备
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETCOUNT_PARAMENT 0x120F0020    //参数错误
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETCOUNT_NOTFOUND 0x120F0021    //没有找到
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETINFO_PARAMENT 0x120F0030     //参数错误
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETINFO_NOTFOUND 0x120F0031     //没有找到
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETINFO_NOTDEVICE 0x120F0032    //此设备索引不存在
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETCTRL_NOTFOUND 0x120F0040     //没有找到
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETCTRL_NOTDEVICE 0x120F0041    //没有设备索引
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETCTRL_STATUS 0x120F0042       //状态错误
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETEXTIP_NOTFOUND 0x120F0050    //没有找到
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETEXTIP_NOTDEVICE 0x120F0051   //此设备索引不存在
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETEXTIP_STATUS 0x120F0052      //HTTP状态错误
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETMAPPING_PARAMENT 0x120F0060  //获取映射信息失败,参数错误
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETMAPPING_NOTFOUND 0x120F0061  //没有找到指定UPNP客户端
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETMAPPING_NOTDEVICE 0x120F0062 //没有找到指定UPNP设备
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_GETMAPPING_STATUS 0x120F0063    //HTTP返回状态错误
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_ADDMAPPING_PARAMENT 0x120F0070  //参数错误,添加映射失败
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_ADDMAPPING_NOTFOUND 0x120F0071  //没有找到
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_ADDMAPPING_NOTDEVICE 0x120F0072 //没有设备
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_ADDMAPPING_STATUS 0x120F0073    //状态错误,添加失败
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_DELMAPPING_PARAMENT 0x120F0080  //参数错误,删除失败
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_DELMAPPING_NOTFOUND 0x120F0081  //没有找到指定句柄
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_DELMAPPING_NOTDEVICE 0x120F0082 //没有找到设备
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_DELMAPPING_STATUS 0x120F0083    //设备端返回状态失败
//////////////////////////////////////////////////////////////////////////
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_XML_GETINFO_NOTNODE 0x120F0100    //获取信息失败,没有关键节点
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_XML_GETCTRL_NOTNODE 0x120F0110    //获取控制节点信息失败
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_XML_GETEXT_NOTNODE 0x120F0120     //获取外部节点失败
#define ERROR_RFCCOMPONENTS_UPNP_CLIENT_XML_GETMAP_NOTNODE 0x120F0130     //获取映射节点失败
