#pragma once
/********************************************************************
//	Created:	2013/1/20  22:41
//	File Name: 	G:\U_DISK_Path\NetSocketEngine\NetEngine_AuthorizeReg\NetEngine_AuthRegService\AuthRegService_Error.h
//	File Path:	G:\U_DISK_Path\NetSocketEngine\NetEngine_AuthorizeReg\NetEngine_AuthRegService
//	File Base:	AuthRegService_Error
//	File Ext:	h
//  Project:    NetSocketEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	网络验证服务器错误表
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                         导出的错误表
//////////////////////////////////////////////////////////////////////////
/************************************************************************/
/*                         网络协议错误                                 */
/************************************************************************/
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_INIT_PARAMENT 0x30D0000       //参数错误，无法继续
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_INIT_CREATETHREAD 0x30D0001   //创建线程失败
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETCLIENT_PARAMENT 0x30D0010  //参数错误
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETCLIENT_NOTFOUND 0x30D0011  //没有找到客户端
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETTIME_PARAMENT 0x30D0020    //参数错误，获取失败
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETTIME_NOTFOUND 0x30D0021    //没有找到制定的客户端
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_SEND_PARAMENT 0x30D0030       //参数错误，发送失败
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_RECVMSG_PARAMENT 0x30D0040    //参数错误，数据接受数据失败
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_RECVMSG_NOTPROTOCOL 0x30D0041 //不是验证协议
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_RECVMSG_NOTSUPPORT 0x30D0042  //不支持此协议
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_LOGIN_PARAMENT 0x30D0050      //参数错误
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_LOGIN_ISLOGIN 0x30D0051       //用户已经登陆，无法第二次登陆
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_LOGIN_PASSWORD 0x30D0052      //用户密码错误，无法继续
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_LOGIN_NOTPAY 0x30D0053        //没有付费的用户
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_LOGIN_NOTTIME 0x30D0054       //登陆失败，注册用户的时间没有了
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_DELETE_PARAMENT 0x30D0060     //参数错误，删除失败
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_DELETE_MATCH 0x30D0061        //验证失败，身份，QQ等信息验证失败
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETPASS_PARAMENT 0x30D0070    //参数错误
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETPASS_MATCH 0x30D0071       //找回密码失败，匹配资料错误
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETADDR_PARAMENT 0x30D0080    //获取失败，参数错误
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETADDR_NOTFOUND 0x30D0081    //没有找到
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETUSER_PARAMENT 0x30D0090    //获取失败,参数错误
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_GETUSER_NOTFOUND 0x30D0091    //没有找到
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_SETUSER_PARAMENT 0x30D00A0    //参数错误
#define ERROR_AUTHORIZEREG_SERVICE_NETWORK_SETUSER_NOTFOUND 0x30D00A1    //没有找到
/************************************************************************/
/*                         数据库错误                                     */
/************************************************************************/
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_INIT_CREATETABLE 0x30D1001   //创建表失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_REGISERT_EXIST 0x30D1010     //用户已经存在
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_REGISERT_INSERT 0x30D1011    //插入内容失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_QUERY_NOTUSER 0x30D1020      //用户不存在
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_QUERY_GETTABLE 0x30D1021     //获取表失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_QUERY_SERIAL 0x30DAA22       //不存在的序列号
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_DELETE_EXEC 0x30D1030        //删除执行失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_SERIALINSERT_ISFAILED 0x30D1040 //序列号插入失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_SERIALINSERT_EXIST 0x30D1041 //序列卡已经存在
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_SERIALDEL_ISFAILED 0x30D1042 //序列号删除失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_PAY_PARAMENT 0x30D1050       //充值失败，参数错误
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_PAY_NOTSUPPORT 0x30D1051     //不支持的充值卡
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_PAY_UPDATAUSEDNAME 0x30D1052 //更新序列卡使用者失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_PAY_ISUSED 0x30D1053         //充值卡已经被使用
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_PAYTIME_NOTMATCH 0x30D1060   //充值方式不匹配
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_PAYTIME_UPDATATYPE 0x30D1061 //更新用户充值卡类型失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_PAYTIME_GETTIME 0x30D1062    //获取时间结构失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_PAYTIME_UPDATA 0x30D1063     //更新数据库失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_LEAVE_UPDATA 0x30D10A0       //离开处理失败，更新数据库失败
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_LEAVE_UNKNOWTYPE 0x30D10A1   //无法识别的卡的类型，无法正确处理离开消息
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_QUERYALL_GETTABLE 0x30D10B0  //获取表失败，内部数据库错误
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_QUERYALL_NONE 0x30D10B1      //获取失败，没有任何记录
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_TRYINSERT_PARAMENT 0x30D10C0 //试用插入失败,参数错误
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_TRYINSERT_EXIST 0x30D10C1    //此序列号存在,无法继续
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_TRYQUERY_PARAMENT 0x30D10D0  //查询试用序列号失败,参数错误
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_TRYQUERY_NONE 0x30D10D1      //查询的内容为空
#define ERROR_AUTHORIZEREG_SERVICE_DATABASE_TRYDELETE_PARAMENT 0x30D10E0 //删除失败,参数错误
