#pragma once
/********************************************************************
//    Created:     2021/07/20  13:23:07
//    File Name:   D:\XEngine\XEngine_SourceCode\XEngine_HelpComponents\HelpComponents_Authorize\Authorize_Error.h
//    File Path:   D:\XEngine\XEngine_SourceCode\XEngine_HelpComponents\HelpComponents_Authorize
//    File Base:   Authorize_Error
//    File Ext:    h
//    Project:     XEngine(网络通信引擎)
//    Author:      qyt
//    Purpose:     错误导出表
//    History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                    序列卡授权导出错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_CREATOR_PARAMEN 0x50A0001   //参数不合适
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_CREATOR_NOTSUPPORT 0x50A0002//不支持此生成类型
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_GETTYPE_PARAMENT 0x50A0010  //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_GETTYPE_BUFFER 0x50A0021    //这个缓冲区有问题，获取卡类型失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_GETTYPE_CUSTOM 0x50A0022    //获取自定义时间序列号的过期时间失败。
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_GETTYPE_UNKNOW 0x50A0023    //获取类型失败，这个类型未知
//////////////////////////////////////////////////////////////////////////
//                    本地授权导出错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_PARAMENT 0x50A1000  //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_CONNECT 0x50A1001   //连接信息写入失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_APPINFO 0x50A1002   //程序信息写入失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_AUTHREG 0x50A1003   //添加注册信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SERIAL 0x50A1004    //写入序列号失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_USER 0x50A1005      //写入用户信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_PARAMENT 0x50A1010   //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_CONNECT 0x50A1011    //获取连接信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_APPINFO 0x50A1012    //获取版本号失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_AUTHREG 0x50A1013    //获取注册信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_SERIAL 0x50A1014     //获取序列号失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_USER 0x50A1013       //获取用户信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_PARAMENT 0x50A1020   //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_NOTREG 0x50A1021     //没有注册
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_NOTHASTIME 0x50A1022 //没有可用时间
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_NOTSUPPORT 0x50A1023 //不支持的获取类型
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_TIMEOUT 0x50A1024    //CDKEY已经超时,没有可用时间
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_UNKNOW 0x50A1025     //注册类型不正确
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_TEMP 0x50A1026       //临时版本已不可用
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_EXPIRED 0x50A1027    //已经过期的CDKEY,无法继续使用
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITETIME_PARAMENT 0x50A1030 //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITETIME_OPENFILE 0x50A1031 //文件不存在
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITETIME_SETFILE 0x50A1032  //设置文件失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READTIME_OPENFILE 0x50A1040  //文件不存在
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READTIME_TIMELIST 0x50A1041  //不存在时间列表
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READTIME_MALLOC 0x50A1042    //申请内存失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READTIME_READ 0x50A1043      //读取文件失败