#pragma once
/********************************************************************
//    Created:     2021/07/20  13:23:07
//    File Name:   D:\XEngine\XEngine_SourceCode\XEngine_HelpComponents\HelpComponents_Authorize\Authorize_Error.h
//    File Path:   D:\XEngine\XEngine_SourceCode\XEngine_HelpComponents\HelpComponents_Authorize
//    File Base:   Authorize_Error
//    File Ext:    h
//    Project:     XEngine(网络通信引擎)
//    Author:      qyt
//    Purpose:     错误导出表
//    History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                    序列卡授权导出错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_CREATOR_PARAMEN 0x70E0001   //参数不合适
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_CREATOR_NOTSUPPORT 0x70E0002//不支持此生成类型
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_GETTYPE_PARAMENT 0x70E0010  //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_GETTYPE_BUFFER 0x70E0021    //这个缓冲区有问题，获取卡类型失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_GETTYPE_CUSTOM 0x70E0022    //获取自定义时间序列号的过期时间失败。
#define ERROR_HELPCOMPONENTS_AUTHORIZE_SERIAL_GETTYPE_UNKNOW 0x70E0023    //获取类型失败，这个类型未知
//////////////////////////////////////////////////////////////////////////
//                    本地授权导出错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_PARAMENT 0x70E1001  //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_CREATE 0x70E1002    //创建文件失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_ADDNAME 0x70E1003   //添加应用名称失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_ADDVER 0x70E1004    //添加版本号失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_ADDCONN 0x70E1005   //添加连接信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SETPORT 0x70E1006   //设置端口失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_ADDREG 0x70E1007    //添加注册信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SETTYPE 0x70E1008   //设置硬件码类型失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SETREGTYPE 0x70E1009//设置注册类型失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_ADDTIMER 0x70E100A  //添加注册时间信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SETHAVETIME 0x70E100B//设置拥有时间失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SETLEFTTIME 0x70E100C//设置超时时间失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SETUSER 0x70E100D    //设置用户名失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SETCONTACT 0x70E100E//设置联系方式失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_WRITEKEY_SETCUSTOM 0x70E100F //设置自定义数据失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_PARAMENT 0x70E1010   //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_OPENFILE 0x70E1011   //打开目标文件失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_NAME 0x70E1012       //获取名称失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_VER 0x70E1013        //获取版本号失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_CONNADDR 0x70E1014   //获取连接地址失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_AUTHCODE 0x70E1015   //获取硬件码失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_AUTHTIMER 0x70E1016  //获取注册时间失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_AUTHLTIME 0x70E1017  //获取过期时间失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_AUTHUSER 0x70E1018   //获取用户信息失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_AUTHCONTACT 0x70E1019//获取联系方式失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_READKEY_AUTHUSERCUSTOM 0x70E101A//获取用户自定义数据失败
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_PARAMENT 0x30C1020   //参数错误
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_NOTREG 0x30C1021     //没有注册
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_NOTHASTIME 0x30C1022 //没有可用时间
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_NOTSUPPORT 0x30C1023 //不支持的获取类型
#define ERROR_HELPCOMPONENTS_AUTHORIZE_LOCAL_GETTIME_TIMEOUT 0x30C1024    //CDKEY已经超时,没有可用时间