#pragma once
/********************************************************************
//	Created:	2017/6/23   21:50
//	Filename: 	G:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_HelpComponents\HelpComponents_BinPack\BINPack_Define.h
//	File Path:	G:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_HelpComponents\HelpComponents_BinPack
//	File Base:	BINPack_Define
//	File Ext:	h
//  Project:    NetEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	二进制文件数据打包模块导出函数
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                    导出函数
//////////////////////////////////////////////////////////////////////////
extern "C" bool BINPack_GetLastError(int *pInt_SysError = NULL);
/************************************************************************/
/*                    二进制打包工具                                    */
/************************************************************************/
/********************************************************************
函数名称：BINPack_Packet_Init
函数功能：初始化一个二进制打包管理器
 参数.一：pxhNet
  In/Out：Out
  类型：文件句柄
  可空：N
  意思：导出获取到的句柄
 参数.二：lpszFileName
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：你要创建的二进制打包文件名
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool BINPack_Packet_Init(XNETHANDLE *pxhFile, LPCXSTR lpszFileName);
/********************************************************************
函数名称：BINPack_Packet_Push
函数功能：压入一个文件到二进制包中
 参数.一：xhFile
  In/Out：In
  类型：文件句柄
  可空：N
  意思：输入你刚才初始化的网络句柄
 参数.二：lpszFileName
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：要打包的文文件,这个参数和第五个参数不能同时为NULL
 参数.三：lpszMemBuffer
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：如果这个参数不为NULL,那么第二个参数必须为NULL,表示写内存数据为文件
 参数.四：nMemLen
  In/Out：In
  类型：整数型
  可空：Y
  意思：内存数据大小
 参数.五：enEncrypto
  In/Out：In
  类型：枚举型
  可空：Y
  意思：加密类型
 参数.六：enPAYLoad
  In/Out：In
  类型：枚举型
  可空：Y
  意思：负载的类型
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool BINPack_Packet_Push(XNETHANDLE xhFile, LPCXSTR lpszFileName = NULL, LPCXSTR lpszMemBuffer = NULL, int nMemLen = 0, ENUM_XENGINE_PROTOCOLHDR_CRYPTO_TYPE enEncrypto = ENUM_XENGINE_PROTOCOLHDR_CRYPTO_TYPE_UNKNOW, ENUM_XENGINE_PROTOCOLHDR_PAYLOAD_TYPE enPAYLoad = ENUM_XENGINE_PROTOCOLHDR_PAYLOAD_TYPE_UNKNOW);
/********************************************************************
函数名称：BINPack_Packet_Close
函数功能：关闭一个二进制包管理器
 参数.一：xhFile
  In/Out：In
  类型：文件句柄
  可空：N
  意思：要关闭的文件句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：如果打包完毕,需要调用此函数关闭
*********************************************************************/
extern "C" bool BINPack_Packet_Close(XNETHANDLE xhFile);
/********************************************************************
函数名称：BINPack_Packet_Package
函数功能：把文件队列中的数据打包成文件
 参数.一：xhFile
  In/Out：In
  类型：文件句柄
  可空：N
  意思：要打包的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool BINPack_Packet_Package(XNETHANDLE xhFile);
/********************************************************************
函数名称：BINPack_Packet_GetInfo
函数功能：获取打包器信息
 参数.一：xhFile
  In/Out：In
  类型：文件句柄
  可空：N
  意思：要打包的句柄
 参数.二：pInt_Count
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出打包的个数
 参数.三：pInt_Size
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出打包的所有大小
 参数.四：pInt_FileSize
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出打包的文件总大小
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool BINPack_Packet_GetInfo(XNETHANDLE xhFile, int* pInt_Count = NULL, __int64x* pInt_Size = NULL, __int64x* pInt_FileSize = NULL);
/************************************************************************/
/*                    二进制解包工具                                    */
/************************************************************************/
/********************************************************************
函数名称：BINPack_UnPack_Init
函数功能：解包函数初始化
 参数.一：pxhFile
  In/Out：Out
  类型：文件句柄
  可空：N
  意思：导出初始化的文件句柄
 参数.二：lpszFileName
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：要解压的文件
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool BINPack_UnPack_Init(XNETHANDLE *pxhFile, LPCXSTR lpszFileName);
/********************************************************************
函数名称：BINPack_UnPack_Get
函数功能：从一个打包的二进制数据中获取一段数据
 参数.一：xhFile
  In/Out：In
  类型：文件句柄
  可空：N
  意思：输入你刚才初始化的网络句柄
 参数.二：lpszFileName
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：获取到的数据是否写成文件,如果为NULL,那么下一个参数不能为NULL
 参数.三：pszMemBuffer
  In/Out：In
  类型：字符指针
  可空：Y
  意思：获取到的文件导出到内存
 参数.四：pIntMemLen
  In/Out：In
  类型：整数型指针
  可空：Y
  意思：输入你提供的大小,输出真实大小,不够将返回错误码
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool BINPack_UnPack_Get(XNETHANDLE xhFile, LPCXSTR lpszFileName = NULL, XCHAR *pszMemBuffer = NULL, int *pIntMemLen = NULL);
/********************************************************************
函数名称：BINPack_UnPack_Close
函数功能：关闭一个二进制包管理器
 参数.一：xhFile
  In/Out：In
  类型：文件句柄
  可空：N
  意思：要关闭的文件句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：如果打包完毕,需要调用此函数关闭
*********************************************************************/
extern "C" bool BINPack_UnPack_Close(XNETHANDLE xhFile);
/********************************************************************
函数名称：BINPack_UnPack_GetInfo
函数功能：获取信息
 参数.一：xhFile
  In/Out：In
  类型：文件句柄
  可空：N
  意思：要操作的文件句柄
 参数.二：pInt_AllSize
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出要解包文件的总大小
 参数.三：pInt_FSize
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出只是文件的总大小
 参数.四：pInt_Count
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出文件个数
 参数.五：pInt_Index
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出当前索引
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool BINPack_UnPack_GetInfo(XNETHANDLE xhFile, __int64x* pInt_AllSize = NULL, __int64x* pInt_FSize = NULL, int* pInt_Count = NULL, int* pInt_Index = NULL);
/********************************************************************
函数名称：BINPack_UnPack_GetType
函数功能：获取当前文件类型
 参数.一：xhFile
  In/Out：In
  类型：文件句柄
  可空：N
  意思：要操作的文件句柄
 参数.二：penEncrypto
  In/Out：Out
  类型：枚举型指针
  可空：Y
  意思：输出加密类型
 参数.三：penPAYLoad
  In/Out：Out
  类型：枚举型指针
  可空：Y
  意思：输出负载类型
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool BINPack_UnPack_GetType(XNETHANDLE xhFile, ENUM_XENGINE_PROTOCOLHDR_CRYPTO_TYPE* penEncrypto = NULL, ENUM_XENGINE_PROTOCOLHDR_PAYLOAD_TYPE* penPAYLoad = NULL);