#pragma once
/********************************************************************
//	Created:	2017/6/23   20:46
//	Filename: 	G:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_HelpComponents\HelpComponents_BinPack\BINPack_Error.h
//	File Path:	G:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_HelpComponents\HelpComponents_BinPack
//	File Base:	BINPack_Error
//	File Ext:	h
//  Project:    NetEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	二进制包管理器错误导出
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                        二进制打包错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_INIT_PARAMENT 0x70A0001     //参数错误
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_INIT_CREATEFILE 0x70A0002   //打开文件失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_INIT_WRITEHDR 0x70A0003     //写入文件头失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_PUSH_PARAMENT 0x70A0010     //参数错误
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_PUSH_NOTFOUND 0x70A0011     //没有找到
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_PUSH_CUSHDR 0x70A0012       //写入自定义头失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_PUSH_GETSIZE 0x70A0013      //获取文件大小失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_PUSH_WRITEHDR 0x70A0014     //写入文件包头失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_PUSH_MALLOC 0x70A0015       //申请内存失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_CLOSE_NOTFOUND 0x70A0020    //关闭失败,没有找到
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_CLOSE_SEEK 0x70A0021        //移动文件指针失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_CLOSE_WRITEHDR 0x70A0022    //重写文件头失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_ENCRYPT_PARAMENT 0x70A0030  //参数错误
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_ENCRYPT_OPENSRC 0x70A0031   //打开原始文件失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_ENCRYPT_OPENDST 0x70A0032   //打开目标文件失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_ENCRYPT_WRITE 0x70A0033     //写入文件失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_GETINFO_PARAMENT 0x70A0040  //参数错误
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_PACKET_GETINFO_NOTFOUND 0x70A0041  //没有找到指定文件句柄
//////////////////////////////////////////////////////////////////////////
//                        二进制解包错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_INIT_PARAMENT 0x70A1000     //初始化失败,参数错误
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_INIT_OPENFILE 0x70A1001     //打开文件失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_INIT_SIZE 0x70A1002         //文件大小不对，不是正确的包
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_INIT_HDR 0x70A1003          //文件头不对，不是正确的打包文件
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_INIT_PASS 0x70A1004         //密码不对，无法处理
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GET_PARAMENT 0x70A1010      //获取失败,参数错误
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GET_NOTFOUND 0x70A1011      //获取失败,没有找到可用的句柄
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GET_GETHDR 0x70A1012        //获取头失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GET_CUSLEN 0x70A1013        //自定义长度缓冲区不够
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GET_CUSDATA 0x70A1014       //获取自定义数据失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GET_DATALEN 0x70A1015       //数据长度不够
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GET_CREATE 0x70A1016        //创建文件失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GET_MALLOC 0x70A1017        //申请内存失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_EDECRYPT_PARAMENT 0x70A1020 //参数错误解密失败
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GETINFO_PARAMENT 0x70A1030  //参数错误
#define ERROR_XENGINE_HELPCOMPONENTS_BINPACK_UNPACK_GETINFO_NOTFOUND 0x70A1031  //没有找到指定文件句柄
