#pragma once
/********************************************************************
//	Created:	2012/5/19  16:23
//	File Name: 	J:\U_DISK_Path\NetSocketEngine\NetEngine_HelpComponents\NetComponents_DataBase\DataBase_Error.h
//	File Path:	J:\U_DISK_Path\NetSocketEngine\NetEngine_HelpComponents\NetComponents_DataBase
//	File Base:	DataBase_Error
//	File Ext:	h
//  Project:    NetSocketEngine(网络通信引擎)
//	Author:		dowflyon
//	Purpose:	数据库错误码导出表
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                       数据库错误
//////////////////////////////////////////////////////////////////////////
/************************************************************************/
/*                       SQLITE数据库错误表                             */
/************************************************************************/
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_OPEN_NOTEXIST 0x50D0000     //文件不存在，打开失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_OPEN_ISFAILED 0x50D0001     //打开数据库失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_OPEN_MALLOC 0x50D0002       //申请内存失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_CREATE_ISEXIST 0x50D0020    //文件已经存在，请删除后继续
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_CREATE_ISFAILED 0x50D0021   //创建数据库失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_EXEC_PARAMENT 0x50D0030     //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_EXEC_ISFAILED 0x50D0031     //执行SQL语句失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_EXEC_NOTFOUND 0x50D0032     //没有找打指定句柄
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_GETTABLE_PARAMENT 0x50D0040 //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_GETTABLE_NOTFOUND 0x50D0041 //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_GETTABLE_ISFAILED 0x50D0042 //执行失败,内部错误
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_EXEQUERY_PARAMENT 0x50D0050 //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_EXEQUERY_NOTFOUND 0x50D0051 //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_EXEQUERY_ISFAILED 0x50D0052 //执行失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_DBEXIST_PARAMENT 0x50D0060  //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_DBEXIST_NOTFOUND 0x50D0061  //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_DBEXIST_PREPARE 0x50D0062   //解析参数失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_DBEXIST_STEP 0x50D0063      //单步执行失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_DBEXIST_FINAL 0x50D0064     //完成解析失败
#define ERROR_HELPCOMPONENTS_DATABASE_SQLITE_DBEXIST_NOTRECORD 0x50D0065 //没有记录集
/************************************************************************/
/*                       MYSQL数据库错误表                              */
/************************************************************************/
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CONNECT_MYSQL 0x50D1001      //初始化MYSQL内存失败0x50D1001
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CONNECT_SETTIMEOUT 0x50D1002 //设置连接超时时间失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CONNECT_ISFAILED 0x50D1004   //连接到MYSQL数据库服务器失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CONNECT_SETCHAR 0x50D1005    //设置字符集失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CONNECT_MULTISTREAM 0x50D1006//设置多语句支持失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CONNECT_MALLOC 0x50D1007     //申请内存失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_EXEC_PARAMENT 0x50D1010      //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_EXEC_NOTFOUND 0x50D1011      //没有找到句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_EXEC_QUERY 0x50D1013         //执行非查询语句失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_EXECQUERY_PARAMENT 0x50D1020 //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_EXECQUERY_NOTFOUND 0x50D1021 //没有找到句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_EXECQUERY_ISFAILED 0x50D1022 //执行查询语句失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_EXECQUERY_NODATA 0x50D1023   //没有数据，查询失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_EXECQUERY_ISNULL 0x50D1024   //获取结果集错误，无法继续
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_GETRESULT_NOTFOUND 0x50D1030 //获取失败，句柄错误
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_GETRESULT_ISNULL 0x50D1031   //获取查询结果集失败，为空
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_GETRESULT_NOTRESULT 0x50D1032//没有找到记录集句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_GETLENGTH_NOTFOUND 0x50D1040 //获取失败，句柄错误
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_GETLENGTH_ISNULL 0x50D1041   //获取查询结果集失败，为空
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_GETLENGTH_NOTRESULT 0x50D1042//没有找到记录集句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_FREERESULT_NOTFOUND 0x50D1050//没有找到句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_GETRESULT_NOTREULT 0x50D1051 //没有找到记录集句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CHANGEUSER_NOTFOUND 0x50D1060//没有找到句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CHANGEUSER_ISFAILED 0x50D1061//改变错误，可能用户名和密码不正确
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CHANGEDB_NOTFOUND 0x50D1070  //没有找到句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CHANGEDB_ISFAILED 0x50D1071  //改变失败，可能DB不存在
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CODER_PARAMENT 0x50D1080     //参数错误，无法继续转换
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CODER_NOTFOUND 0x50D1081     //没有找到句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_CODER_CODER 0x50D1082        //转换失败。内部错误
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_QUERY_PARAMENT 0x50D1090     //执行影响查询失败，参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_QUERY_NOTFOUND 0x50D1091     //没有找到指定句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_QUERY_ISFAILED 0x50D1092     //执行查询语句失败
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_QUERY_NODATA 0x50D1093       //没有数据，没有被影响的数据
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_PING_NOTFOUND 0x50D10A0
#define ERROR_HELPCOMPONENTS_DATABASE_MYSQL_PING_ISFAILED 0x50D10A1      //失败,可能
/************************************************************************/
/*                       MYSQL数据库错误表                                */
/************************************************************************/
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_CONNECT_PARAMENT 0x50D4000   //参数错误，无法继续
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_CONNECT_MALLOC 0x50D4001     //申请内存失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_CONNECT_FAILED 0x50D4002     //链接服务器失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_CONNECT_POOL 0x50D4003       //创建连接池失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_EXECMD_PARAMENT 0x50D4010    //参数错误，执行命令失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_EXECMD_NOTFOUND 0x50D4011    //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_EXECMD_GETREPLY 0x50D4012    //获取回复失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_INSERT_PARAMENT 0x50D4020    //参数错误，无法继续
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_INSERT_NOTFOUND 0x50D4021    //没有找到指定的句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_INSERT_GETCOLL 0x50D4022     //获取集合失败，可能数据库或者表不存在
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_INSERT_FAILED 0x50D4023      //插入失败，内部错误
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_FIND_PARAMENT 0x50D4030      //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_FIND_NOTFOUND 0x50D4031      //没有句柄
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_FIND_GETCOLL 0x50D4032       //获取集合失败，可能数据库或者表不存在
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_FIND_FAILED 0x50D4033        //查找失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_UPDATE_PARAMENT 0x50D4040    //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_UPDATE_NOTFOUND 0x50D4041    //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_UPDATE_GETCOLL 0x50D4042     //获取集合失败，可能数据库或者表不存在
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_UPDATE_FAILED 0x50D4043      //更新失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_DELETE_PARAMENT 0x50D4050    //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_DELETE_NOTFOUND 0x50D4051    //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_DELETE_GETCOLL 0x50D4052     //获取集合失败，可能数据库或者表不存在
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_DELETE_FAILED 0x50D4053      //删除失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_COUNT_PARAMENT 0x50D4060     //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_COUNT_NOTFOUND 0x50D4061     //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_COUNT_GETCOLL 0x50D4062      //获取集合失败，可能数据库或者表不存在
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_DELCOLL_PARAMENT 0x50D4070   //参数错误，删除集合失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_DELCOLL_NOTFOUND 0x50D4071   //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_DELCOLL_GETCOLL 0x50D4072    //获取集合失败
#define ERROR_HELPCOMPONENTS_DATABASE_MONGO_DELCOLL_FAILED 0x50D4073     //删除集合失败，可能不存在
/************************************************************************/
/*                       POSTGRE数据库错误表                              */
/************************************************************************/
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_CONNECT_PARAMENT 0x50D5000  //参数错误，无法继续
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_CONNECT_MALLOC 0x50D5001    //申请内存失败，无法继续
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_CONNECT_FAILED 0x50D5002    //链接服务器失败
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_EXEC_PARAMENT 0x50D5010     //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_EXEC_NOTFOUND 0x50D5011     //没有找到，无法继续
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_EXEC_FAILED 0x50D5012       //执行命令失败
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_QUERY_PARAMENT 0x50D5020    //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_QUERY_NOTFOUND 0x50D5021    //没有找到，无法继续
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_QUERY_MALLOC 0x50D5022      //申请内存失败
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_QUERY_FAILED 0x50D5023      //执行命令失败
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_GET_PARAMENT 0x50D5030      //参数错误
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_GET_NOTDB 0x50D5031         //没有找到句柄
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_GET_NOTRESULT 0x50D5032     //没有这个记录集指针
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_GET_NODATA 0x50D5033        //没有数据
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_FREE_NOTFOUND 0x50D5040     //没有找到数据库句柄
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTIFYSTART_PARAMENT 0x50D5050  //参数错误，无法继续
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTIFYSTART_NOTFOUND 0x50D5051  //没有找到数据库句柄
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTIFYSTART_FAILED 0x50D5052    //启动监听失败
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTIFYSTART_MALLOC 0x50D5053    //申请内存失败
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTIFYSTART_SOCKET 0x50D5054    //创建监听套接字失败
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTIFYSTART_THREAD 0x50D5055    //创建监听线程失败
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTIFYSTOP_NOTDB 0x50D5060      //没有数据库句柄
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTIFYSTOP_NOTNOTIFY 0x50D5061  //没有通知句柄
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTFOUND 0x50D5070          //没有找到
#define ERROR_HELPCOMPONENTS_DATABASE_POSTGRE_NOTCONNECT 0x50D5071        //没有链接
/************************************************************************/
/*                       MSSQL数据库错误导出                            */
/************************************************************************/
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_INIT_PARAMENT 0x50D3001
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_INIT_CREATEINSTANCE 0x50D3002
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_INIT_CONNECT 0x50D3003
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_SELECT_PARAMENT 0x50D3010
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_SELECT_CREATEINSTANCE 0x50D3011
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_SELECT_QUERY 0x50D3012
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_GETNEXT_PARAMENT 0x50D3020
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_GETNEXT_ISNULL 0x50D3021
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_GETNEXT_MOVEREC 0x50D3022
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_CLOSE_RECORDSET 0x50D3030
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_CLOSE_CONNECT 0x50D3031
//////////////////////////////////////////////////////////////////////////
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_EX_INIT_CREATEGUID 0x50D3100
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_EX_INIT_NEWCLASS 0x50D3101
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_EX_SELECT_NOTFOUND 0x50D3101
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_EX_GETNEXT_NOTFOUND 0x50D3101
#define ERROR_HELPCOMPONENTS_DATABASE_MSSQL_EX_CLOSE_NOTFOUND 0x50D3101