#pragma once
/********************************************************************
//	Created:	2014/1/27  11:47
//	File Name: 	/NetEngine_Linux/NetEngine_SourceCode/NetEngine_NetHelp/NetEngine_APIHelp/APIHelp_Define.h
//	File Path:	/NetEngine_Linux/NetEngine_SourceCode/NetEngine_NetHelp/NetEngine_APIHelp/
//	File Base:	APIHelp_Define.h
//	File Ext:	h
//  Project:    NetSocketEngine(网络通信引擎) For Linux
//	Author:		dowflyon
//	Purpose:	导出的网络帮助API函数库
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                        导出的类型定义
//////////////////////////////////////////////////////////////////////////
#define XHtons APIHelp_Endain_htons
#define XNtohs APIHelp_Endain_ntohs
#define XHtonl APIHelp_Endain_htonl
#define XNtohl APIHelp_Endain_ntohl
#define XHtonl64 APIHelp_Endain_hl64ton
#define XNtohl64 APIHelp_Endain_ntohl64
//////////////////////////////////////////////////////////////////////////
//                        导出的函数
//////////////////////////////////////////////////////////////////////////
extern "C" XLONG APIHelp_GetLastError(int *pInt_SysError = XNULL);
//////////////////////////////////////////////////////////////////////////
/*********************************************************************************
*                          字节序转换导出函数                                    *
*********************************************************************************/
/********************************************************************
函数名称：APIHelp_Endain_IsLittle
函数功能：判断是否为小端字节序
返回值
  类型：逻辑型
  意思：返回真为小端字节序,返回假为大端字节序(网络字节序)
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_IsLittle();
/********************************************************************
函数名称：APIHelp_Endain_htons
函数功能：16位主机字节转网络字节序
 参数.一：nValue16
  In/Out：In
  类型：无符号16位整数
  可空：N
  意思：要转换的主机字节序
返回值
  类型：无符号16位整数
  意思：返回网络字节序
备注：
*********************************************************************/
extern "C" XSHOT APIHelp_Endain_htons(XSHOT nValue16);
/********************************************************************
函数名称：APIHelp_Endain_ntohs
函数功能：16位网络字节转主机字节序
 参数.一：nValue16
  In/Out：In
  类型：无符号16位整数
  可空：N
  意思：要转换的网络字节序
返回值
  类型：无符号16位整数
  意思：返回主机字节序
备注：
*********************************************************************/
extern "C" XSHOT APIHelp_Endain_ntohs(XSHOT nValue16);
/********************************************************************
函数名称：APIHelp_Endain_htonl
函数功能：32位主机字节转网络字节序
 参数.一：nValue32
  In/Out：In
  类型：无符号32位整数
  可空：N
  意思：要转换的主机字节序
返回值
  类型：无符号32位整数
  意思：返回网络字节序
备注：
*********************************************************************/
extern "C" XUINT APIHelp_Endain_htonl(XUINT nValue32);
/********************************************************************
函数名称：APIHelp_Endain_ntohl
函数功能：32位网络字节转主机字节序
 参数.一：nValue32
  In/Out：In
  类型：无符号32位整数
  可空：N
  意思：要转换的网络字节序
返回值
  类型：无符号32位整数
  意思：返回主机字节序
备注：
*********************************************************************/
extern "C" XUINT APIHelp_Endain_ntohl(XUINT nValue32);
/********************************************************************
函数名称：APIHelp_Endain_hl64ton
函数功能：64位主机字节转网络字节序
 参数.一：ullHost
  In/Out：In
  类型：无符号64位整数
  可空：N
  意思：要转换的主机字节序
返回值
  类型：无符号64位整数
  意思：返回网络字节序
备注：
*********************************************************************/
extern "C" __int64u APIHelp_Endain_hl64ton(__int64u ullHost);
/********************************************************************
函数名称：APIHelp_Endain_ntohl64
函数功能：64位网络字节转主机字节序
 参数.一：ullNet
  In/Out：In
  类型：无符号64位整数
  可空：N
  意思：要转换的网络字节序
返回值
  类型：无符号64位整数
  意思：返回主机字节序
备注：
*********************************************************************/
extern "C" __int64u APIHelp_Endain_ntohl64(__int64u ullNet);
/********************************************************************
函数名称：APIHelp_Endain_ToHexW8
函数功能：对一个字符指针写入一个指定字符到指定位置
 参数.一：ptszDest
  In/Out：In/Out
  类型：字符指针
  可空：N
  意思：输入要操作的字符指针,输出结果
 参数.二：byValue
  In/Out：In
  类型：字符
  可空：N
  意思：输入要写入的值
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToHexW8(XBYTE* ptszDest, XBYTE byValue);
/********************************************************************
函数名称：APIHelp_Endain_ToHexW16
函数功能：写入一个16位数据到指定字符指针位置
 参数.一：ptszDest
  In/Out：In/Out
  类型：字符指针
  可空：N
  意思：输入要操作的字符指针,输出结果
 参数.二：nValue16
  In/Out：In
  类型：字符
  可空：N
  意思：输入要写入的值
 参数.三：bEndian
  In/Out：In
  类型：字符
  可空：N
  意思：输入的值是否需要转大小端,默认不转(主机字节序)
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToHexW16(XBYTE* ptszDest, XSHOT nValue16, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToHexW24
函数功能：写入一个24位数据到指定字符指针位置
 参数.一：ptszDest
  In/Out：In/Out
  类型：字符指针
  可空：N
  意思：输入要操作的字符指针,输出结果
 参数.二：nValue24
  In/Out：In
  类型：字符
  可空：N
  意思：输入要写入的值
 参数.三：bEndian
  In/Out：In
  类型：字符
  可空：N
  意思：输入的值是否需要转大小端,默认不转(主机字节序)
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToHexW24(XBYTE* ptszDest, XUINT nValue24, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToHexW32
函数功能：写入一个32位数据到指定字符指针位置
 参数.一：ptszDest
  In/Out：In/Out
  类型：字符指针
  可空：N
  意思：输入要操作的字符指针,输出结果
 参数.二：nValue24
  In/Out：In
  类型：字符
  可空：N
  意思：输入要写入的值
 参数.三：bEndian
  In/Out：In
  类型：字符
  可空：N
  意思：输入的值是否需要转大小端,默认不转(主机字节序)
返回值
  类型：逻辑型
  意思：是否成功
备注：支持float类型,要转换float需要按照此方式传递值
      APIHelp_Endain_IntToHexW64(ptszDest, nPos, *(XUINT*)&nValue32);
*********************************************************************/
extern "C" bool APIHelp_Endain_ToHexW32(XBYTE* ptszDest, XUINT nValue32, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToHexW40
函数功能：写入一个40位数据到指定字符指针位置
 参数.一：ptszDest
  In/Out：In/Out
  类型：字符指针
  可空：N
  意思：输入要操作的字符指针,输出结果
 参数.二：nValue40
  In/Out：In
  类型：字符
  可空：N
  意思：输入要写入的值
 参数.三：bEndian
  In/Out：In
  类型：字符
  可空：N
  意思：输入的值是否需要转大小端,默认不转(主机字节序)
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToHexW40(XBYTE* ptszDest, __int64u nValue40, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToHexW48
函数功能：写入一个48位(6个字节)数据到指定字符指针位置
 参数.一：ptszDest
  In/Out：In/Out
  类型：字符指针
  可空：N
  意思：输入要操作的字符指针,输出结果
 参数.二：nValue48
  In/Out：In
  类型：字符
  可空：N
  意思：输入要写入的值
 参数.三：bEndian
  In/Out：In
  类型：字符
  可空：N
  意思：输入的值是否需要转大小端,默认不转(主机字节序)
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToHexW48(XBYTE* ptszDest, __int64u nValue48, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToHexW56
函数功能：写入一个56位(7个字节)数据到指定字符指针位置
 参数.一：ptszDest
  In/Out：In/Out
  类型：字符指针
  可空：N
  意思：输入要操作的字符指针,输出结果
 参数.二：nValue56
  In/Out：In
  类型：字符
  可空：N
  意思：输入要写入的值
 参数.三：bEndian
  In/Out：In
  类型：字符
  可空：N
  意思：输入的值是否需要转大小端,默认不转(主机字节序)
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToHexW56(XBYTE* ptszDest, __int64u nValue56, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToHexW64
函数功能：写入一个64位数据到指定字符指针位置
 参数.一：ptszDest
  In/Out：In/Out
  类型：字符指针
  可空：N
  意思：输入要操作的字符指针,输出结果
 参数.二：nValue24
  In/Out：In
  类型：字符
  可空：N
  意思：输入要写入的值
 参数.三：bEndian
  In/Out：In
  类型：字符
  可空：N
  意思：输入的值是否需要转大小端,默认不转(主机字节序)
返回值
  类型：逻辑型
  意思：是否成功
备注：支持double类型,要转换double需要按照此方式传递值
      APIHelp_Endain_IntToHexW64(ptszDest, nPos, *(__int64u*)&nValue64);
*********************************************************************/
extern "C" bool APIHelp_Endain_ToHexW64(XBYTE* ptszDest, __int64u nValue64, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToR8Hex
函数功能：读取一个字节从字符串中
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的字符串
 参数.二：pbyValue
  In/Out：Out
  类型：字符串
  可空：N
  意思：输出读取到的数据
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToR8Hex(LPCXSTR lpszMsgBuffer, XBYTE* pbyValue);
/********************************************************************
函数名称：APIHelp_Endain_ToR16Hex
函数功能：读取双字从字符串中
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的字符串
 参数.二：pnValue16
  In/Out：Out
  类型：短整数型
  可空：N
  意思：输出读取到的数据
 参数.三：bEndian
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否需要网络字节序转换,默认否
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToR16Hex(LPCXSTR lpszMsgBuffer, XSHOT* pnValue16, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToR24Hex
函数功能：读取3个字节整数型从字符串中
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的字符串
 参数.二：pnValue32
  In/Out：Out
  类型：整数型
  可空：N
  意思：输出读取到的数据
 参数.三：bEndian
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否需要网络字节序转换,默认否
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToR24Hex(LPCXSTR lpszMsgBuffer, XUINT* pnValue24, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToR32Hex
函数功能：读取整数型从字符串中
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的字符串
 参数.二：pnValue32
  In/Out：Out
  类型：整数型
  可空：N
  意思：输出读取到的数据
 参数.三：bEndian
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否需要网络字节序转换,默认否
返回值
  类型：逻辑型
  意思：是否成功
备注：支持float类型获取,直接强制转换即可
      APIHelp_Endain_ToR64Hex(lpszMsgBuffer, (__int64u*)&flValue, bEndian);
*********************************************************************/
extern "C" bool APIHelp_Endain_ToR32Hex(LPCXSTR lpszMsgBuffer, XUINT* pnValue32, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToR40Hex
函数功能：读取整数型从字符串中
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的字符串
 参数.二：pnValue40
  In/Out：Out
  类型：整数型
  可空：N
  意思：输出读取到的数据
 参数.三：bEndian
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否需要网络字节序转换,默认否
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToR40Hex(LPCXSTR lpszMsgBuffer, __int64u* pnValue40, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToR48Hex
函数功能：读取48位(6字节)整数型从字符串中
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的字符串
 参数.二：pnValue48
  In/Out：Out
  类型：64位整数型
  可空：N
  意思：输出读取到的数据
 参数.三：bEndian
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否需要网络字节序转换,默认否
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToR48Hex(LPCXSTR lpszMsgBuffer, __int64u* pnValue48, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToR56Hex
函数功能：读取56位(7字节)整数型从字符串中
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的字符串
 参数.二：pnValue56
  In/Out：Out
  类型：64位整数型
  可空：N
  意思：输出读取到的数据
 参数.三：bEndian
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否需要网络字节序转换,默认否
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Endain_ToR56Hex(LPCXSTR lpszMsgBuffer, __int64u* pnValue56, bool bEndian = false);
/********************************************************************
函数名称：APIHelp_Endain_ToR64Hex
函数功能：读取64位整数型从字符串中
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要读取的字符串
 参数.二：pnValue64
  In/Out：Out
  类型：64位整数型
  可空：N
  意思：输出读取到的数据
 参数.三：bEndian
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否需要网络字节序转换,默认否
返回值
  类型：逻辑型
  意思：是否成功
备注：支持float类型获取,直接强制转换即可
      APIHelp_Endain_ToR64Hex(lpszMsgBuffer, (__int64u*)&dlValue, bEndian);
*********************************************************************/
extern "C" bool APIHelp_Endain_ToR64Hex(LPCXSTR lpszMsgBuffer, __int64u* pnValue64, bool bEndian = false);
/*********************************************************************************
*                          BIT流读写操作导出函数                                 *
*********************************************************************************/
/********************************************************************
函数名称：APIHelp_Stream_Init
函数功能：初始化一个BIT流式操作
 参数.一：lpszBITStream
  In/Out：In
  类型：常量字节指针
  可空：N
  意思：输入要处理的数据
 参数.二：nMSGLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入大小
返回值
  类型：句柄
  意思：返回初始化成功的句柄
备注：
*********************************************************************/
extern "C" XHANDLE APIHelp_Stream_Init(LPCXBTR lpszBITStream, int nMSGLen);
/********************************************************************
函数名称：APIHelp_Stream_Destory
函数功能：销毁流式操作
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool APIHelp_Stream_Destory(XHANDLE xhToken);
/********************************************************************
函数名称：APIHelp_Stream_ReadBit
函数功能：读取指定BIT位个数的值
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：byBITCount
  In/Out：In
  类型：字节型
  可空：N
  意思：输入要操作的BIT位个数
返回值
  类型：整数型
  意思：返回读取的值,<= 0表示错误
备注：
*********************************************************************/
extern "C" XUINT APIHelp_Stream_ReadBit(XHANDLE xhToken, XBYTE byBITCount);
/********************************************************************
函数名称：APIHelp_Stream_ReadUE
函数功能：解码有符号指数哥伦布编码（SE）的值
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
返回值
  类型：整数型
  意思：返回读取的值,<= 0表示错误
备注：H.264编码中，语法元素分为三种类型：无符号指数哥伦布编码（UE）、有符号指数哥伦布编码（SE）和有符号整数（SI）
*********************************************************************/
extern "C" XUINT APIHelp_Stream_ReadUE(XHANDLE xhToken);
/********************************************************************
函数名称：APIHelp_Stream_ReadSE
函数功能：解码 H.264 中的无符号指数哥伦布编码（UE）的值
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：H.264编码中，语法元素分为三种类型：无符号指数哥伦布编码（UE）、有符号指数哥伦布编码（SE）和有符号整数（SI）
*********************************************************************/
extern "C" int APIHelp_Stream_ReadSE(XHANDLE xhToken);
/********************************************************************
函数名称：APIHelp_Stream_ReadSI
函数功能：解码H.264中的有符号整数
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：H.264编码中，语法元素分为三种类型：无符号指数哥伦布编码（UE）、有符号指数哥伦布编码（SE）和有符号整数（SI）
*********************************************************************/
extern "C" int APIHelp_Stream_ReadSI(XHANDLE xhToken);