#pragma once
/********************************************************************
//    Created:     2023/02/02  16:32:18
//    File Name:   D:\XEngine\XEngine_SourceCode\XEngine_NetHelp\NetHelp_BTorrent\BTorrent_Error.h
//    File Path:   D:\XEngine\XEngine_SourceCode\XEngine_NetHelp\NetHelp_BTorrent
//    File Base:   BTorrent_Error
//    File Ext:    h
//    Project:     XEngine
//    Author:      qyt
//    Purpose:     BT下载错误导出
//    History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                      BT下载器错误
//////////////////////////////////////////////////////////////////////////
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_DLOAD_CREATE_PARAMENT 0x060B0001    //创建下载参数错误
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_DLOAD_CREATE_MALLOC 0x060B0002      //创建内存失败
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_DLOAD_UPEVENT_NOTFOUND 0x060B0010   //没有找到
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_DLOAD_QUERY_PARAMENT 0x060B0020     //参数错误
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_DLOAD_QUERY_NOTFOUND 0x060B0021     //没有找到句柄
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_DLOAD_QUERY_NONE 0x060B0022         //没有事件
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_DLOAD_GETSTATUS_PARAMENT 0x060B0030 //参数错误
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_DLOAD_GETSTATUS_NOTFOUND 0x060B0031 //没有找到
//////////////////////////////////////////////////////////////////////////
//                      BT解析器错误
//////////////////////////////////////////////////////////////////////////
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_INIT_PARAMENT 0x060B1001    //参数错误
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_INIT_MALLOC 0x060B1002      //申请内存失败
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_GETNODE_PARAMENT 0x060B1010 //参数错误
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_GETNODE_NOTFOUND 0x060B1011 //没有找到
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_GETTRACKER_PARAMENT 0x060B1020
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_GETTRACKER_NOTFOUND 0x060B1021
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_GETSEED_PARAMENT 0x060B1030
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_GETSEED_NOTFOUND 0x060B1031
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_GETFILE_PARAMENT 0x060B1040
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_PARSE_GETFILE_NOTFOUND 0x060B1041
//////////////////////////////////////////////////////////////////////////
//                      BT解析器错误
//////////////////////////////////////////////////////////////////////////
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_INIT_PARAMENT 0x060B2001  //参数错误,初始化失败
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_INIT_MALLOC 0x060B2002    //申请内存失败
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_NODE_PARAMENT 0x060B2010  //参数错误
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_NODE_NOTFOUND 0x060B2011  //没有找到指定句柄
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_TRACKER_PARAMENT 0x060B2020
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_TRACKER_NOTFOUND 0x060B2021
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_SEEDS_PARAMENT 0x060B2030
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_SEEDS_NOTFOUND 0x060B2031
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_INFO_PARAMENT 0x060B2040
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_INFO_NOTFOUND 0x060B2041
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_FILE_PARAMENT 0x060B2050
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_FILE_NOTFOUND 0x060B2051
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_FILE_FAILED 0x060B2052
#define ERROR_XENGINE_DOWNLOAD_BTORRENT_CREATOR_FILE_PARSE 0x060B2003     //解析文件失败,无法继续