#pragma once
/********************************************************************
//	Created:	2018/1/7   12:27
//	Filename: 	/NetEngine_Linux/NetEngine_SourceCode/NetEngine_XMQCore/NetEngine_XMDDService/XMDDS_Define.h
//	File Path:	/NetEngine_Linux/NetEngine_SourceCode/NetEngine_XMQCore/NetEngine_XMDDService/
//	File Base:	XMDDS_Define
//	File Ext:	h
//  Project:    NetEngine_Linux(网络通信引擎)
//	Author:		Dowflyon
//	Purpose:	消息分发服务导出的函数
//	History:    请注意，这个模块只能用于局域网，而且消息非可靠传输
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                       导出的函数
//////////////////////////////////////////////////////////////////////////
typedef struct tag_DDSService_ScribeMsg
{
    CHAR tszMsgBuffer[4096];
    int nMsgLen;
}DDSSUBSCIRBE_MSGBUFFER;
//////////////////////////////////////////////////////////////////////////
//                       导出的函数
//////////////////////////////////////////////////////////////////////////
//通知消息,域被删除通知(pSt_XDDSProtocol无效),主题删除通知,有发布者创建(XENGINE_COMMUNICATION_PROTOCOL_OPERATOR_CODE_DDS_*)
typedef void(CALLBACK *CALLBACK_NETENGINE_MQCORE_XDDS_COMM_NOTIFY)(int nNotifyEvent,int nDomainId,XENGINE_PROTOCOL_XDDS *pSt_XDDSProtocol,LPVOID lParam);
//////////////////////////////////////////////////////////////////////////
//                       导出的函数
//////////////////////////////////////////////////////////////////////////
extern "C" DWORD XDDS_GetLastError(int *pInt_SysError = NULL);
/*************************************************************************
                        订阅者与发布者公有函数
**************************************************************************/
/********************************************************************
函数名称：XDDS_CommApi_Init
函数功能：初始化DDS服务
 参数.一：lpszCardAddr
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：网卡地址，如果要使用TCP或者在多网卡的情况下，这个参数不能为NULL
 参数.二：nSndPort
  In/Out：In
  类型：整数型
  可空：Y
  意思：协议发送者端口
 参数.三：nRcvPort
  In/Out：In
  类型：整数型
  可空：Y
  意思：协议接受者端口
 参数.四：lpszDDSAddr
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：UDP组播服务地址开始IP地址.直到*.255.255.255 都可分配
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XDDS_CommApi_Init(LPCSTR lpszCardAddr = NULL, int nSndPort = 50901, int nRcvPort = 50902, LPCSTR lpszDDSAddr = _T("234.0.1.1"));
/************************************************************************
函数名称：XDDS_CommApi_Destory
函数功能：销毁DDS服务
返回值
  类型：逻辑型
  意思：是否销毁成功
备注：
************************************************************************/
extern "C" BOOL XDDS_CommApi_Destory();
/********************************************************************
函数名称：XDDS_CommApi_SetAttr
函数功能：设置回调函数
 参数.一：fpCall_XDDSNotify
  In/Out：In/Out
  类型：回调函数
  可空：N
  意思：要注册的回调函数地址
 参数.二：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数参数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XDDS_CommApi_SetAttr(CALLBACK_NETENGINE_MQCORE_XDDS_COMM_NOTIFY fpCall_XDDSNotify, LPVOID lParam = NULL);
/************************************************************************
函数名称：XDDS_CommApi_DomainCreate
函数功能：创建一个域
 参数.一：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：要创建的域ID
返回值
  类型：逻辑型
  意思：是否创建成功
备注：不同域之间无法通信
************************************************************************/
extern "C" BOOL XDDS_CommApi_DomainCreate(int nDomainId);
/************************************************************************
函数名称：XDDS_CommApi_DomainDelete
函数功能：删除一个域
 参数.一：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：要删除的域ID
返回值
  类型：逻辑型
  意思：是否删除成功
备注：
************************************************************************/
extern "C" BOOL XDDS_CommApi_DomainDelete(int nDomainId);
/********************************************************************
函数名称：XDDS_CommApi_TopicCreate
函数功能：创建一个主题
 参数.一：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：创建好的域的ID
 参数.二：lpszTopic
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：要创建的主题名称
 参数.三：bTCP
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：主题的网络类型
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XDDS_CommApi_TopicCreate(int nDomainId, LPCSTR lpszTopic, BOOL bTCP = FALSE);
/************************************************************************
函数名称：XDDS_CommApi_TopicDelete
函数功能：删除一个主题
 参数.一：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：要删除主题所属域
 参数.二：lpszTopic
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：要删除的主题名称
返回值
  类型：逻辑型
  意思：是否成功
备注：
************************************************************************/
extern "C" BOOL XDDS_CommApi_TopicDelete(int nDomainId, LPCSTR lpszTopic);
/********************************************************************
函数名称：XDDS_CommApi_TopicGet
函数功能：获得主题关联信息
 参数.一：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：输入要操作的域
 参数.二：lpszTopic
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的主题
 参数.三：pppSt_DDSProtocol
  In/Out：Out
  类型：三级指针
  可空：N
  意思：输出主题关联信息,这个内存需要释放
 参数.四：pInt_ListCount
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出信息列表个数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XDDS_CommApi_TopicGet(int nDomainId, LPCSTR lpszTopic, XENGINE_PROTOCOL_XDDS * **pppSt_DDSProtocol, int* pInt_ListCount);
/********************************************************************
函数名称：XDDS_CommApi_SocketGet
函数功能：获得接受发送的协议套接字
 参数.一：pSDSocket
  In/Out：Out
  类型：句柄
  可空：N
  意思：输出发送套接字句柄
 参数.二：pRVSocket
  In/Out：Out
  类型：句柄
  可空：N
  意思：输出接受套接字句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XDDS_CommApi_SocketGet(SOCKET* pSDSocket = NULL, SOCKET* pRVSocket = NULL);
/************************************************************************
函数名称：XDDS_CommApi_AddPublish
函数功能：添加一个主题创建者
 参数.一：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：要查找主题所属域
 参数.二：lpszTopic
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：要查找的主题名称
 参数.三：pSt_XDDSProtocol
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入对应信息
返回值
  类型：逻辑型
  意思：是否成功
备注：
************************************************************************/
extern "C" BOOL XDDS_CommApi_AddPublish(int nDomainId, LPCSTR lpszTopic, XENGINE_PROTOCOL_XDDS* pSt_XDDSProtocol);
/************************************************************************
函数名称：XDDS_CommApi_DelPublish
函数功能：删除一个发布者
 参数.一：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：要查找主题所属域
 参数.二：lpszTopic
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：要查找的主题名称
 参数.三：pSt_XDDSProtocol
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入要删除的内容
返回值
  类型：逻辑型
  意思：是否成功
备注：
************************************************************************/
extern "C" BOOL XDDS_CommApi_DelPublish(int nDomainId, LPCSTR lpszTopic, XENGINE_PROTOCOL_XDDS* pSt_XDDSProtocol);
/************************************************************************
函数名称：XDDS_CommApi_GetInfo
函数功能：获取信息
 参数.一：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：要查询的域ID关联的信息
 参数.二：pInt_DataPort
  In/Out：Out
  类型：整数型指针
  可空：Y
  意思：输出数据端口
 参数.三：ptszLocalAddr
  In/Out：In
  类型：字符指针
  可空：Y
  意思：输出设置的网卡IP地址
 参数.四：ptszBroadAddr
  In/Out：In
  类型：字符指针
  可空：Y
  意思：输出设置的协议广播地址
返回值
  类型：逻辑型
  意思：是否获取成功
备注：
************************************************************************/
extern "C" BOOL XDDS_CommApi_GetInfo(int nDomainId, int* pInt_DataPort = NULL, CHAR* ptszLocalAddr = NULL, CHAR* ptszBroadAddr = NULL);
/*************************************************************************
                        导出的发布者函数
**************************************************************************/
/************************************************************************
函数名称：XDDS_Publish_Create
函数功能：创建一个发布者
  参数.一：pxhPublish
   In/Out：Out
   类型：网络句柄指针
   可空：N
   意思：导出发布者创建的句柄
  参数.二：nDomainId
   In/Out：In
   类型：整数型
   可空：N
   意思：发布者所属域ID
  参数.三：lpszTopic
   In/Out：In
   类型：常量字符指针
   可空：N
   意思：要为哪个主题创建发布者
  参数.四：bIsTcp
   In/Out：In
   类型：逻辑型
   可空：Y
   意思：为主题创建的可靠还是非可靠传输
返回值
  类型：逻辑型
  意思：是否创建成功
备注：
************************************************************************/
extern "C" BOOL XDDS_Publish_Create(XNETHANDLE *pxhPublish,int nDomainId,LPCSTR lpszTopic);
/************************************************************************
函数名称：XDDS_Publish_Delete
函数功能：删除一个发布者
  参数.一：xhPublish
   In/Out：In
   类型：网络句柄
   可空：N
   意思：输入要删除的发布者句柄
返回值
  类型：逻辑型
  意思：是否删除成功
备注：请先删除写者在调用此函数
************************************************************************/
extern "C" BOOL XDDS_Publish_Delete(XNETHANDLE xhPublish);
/************************************************************************
函数名称：XDDS_Publish_SendMsg
函数功能：为指定写者发布数据
  参数.一：xhPublish
   In/Out：In
   类型：网络句柄
   可空：N
   意思：写者所属发布者
  参数.二：xhWriter
   In/Out：In
   类型：网络句柄
   可空：N
   意思：写者的句柄
  参数.三：nLen
   In/Out：In
   类型：整数型
   可空：N
   意思：要发送数据的长度
返回值
  类型：逻辑型
  意思：是否发布成功
备注：
************************************************************************/
extern "C" BOOL XDDS_Publish_SendMsg(XNETHANDLE xhPublish,LPCSTR lpszMsgBuffer,int nLen);
/*************************************************************************
                        导出的订阅者函数
**************************************************************************/
/************************************************************************
函数名称：XDDS_SubScribe_Create
函数功能：创建一个订阅者
  参数.一：pxhSubScribe
   In/Out：Out
   类型：网络句柄指针
   可空：N
   意思：导出创建好的订阅者句柄
  参数.二：nDomainId
   In/Out：In
   类型：整数型
   可空：N
   意思：订阅者所属域ID
  参数.三：lpszTopic
   In/Out：In
   类型：常量字符指针
   可空：N
   意思：要为哪个主题创建订阅者
  参数.四：bTcp
   In/Out：In
   类型：逻辑型
   可空：Y
   意思：是否使用TCP，默认UDP
返回值
  类型：逻辑型
  意思：是否创建成功
备注：
************************************************************************/
extern "C" BOOL XDDS_SubScribe_Create(XNETHANDLE *pxhSubScribe,int nDomainId,LPCSTR lpszTopic);
/********************************************************************
函数名称：XDDS_SubScribe_Insert
函数功能：插入一个新的发布信息到订阅者中
 参数.一：xhSubScribe
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的订阅者
 参数.二：nDomainId
  In/Out：In
  类型：整数型
  可空：N
  意思：输入创建的域
 参数.三：pSt_DDSProtocol
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入创建通知的DDS信息
返回值
  类型：逻辑型
  意思：是否成功
备注：当收到创建者通知的时候,这个函数需要订阅者调用,一般情况下,只有TCP才需要调用
*********************************************************************/
extern "C" BOOL XDDS_SubScribe_Insert(XNETHANDLE xhSubScribe, int nDomainId, XENGINE_PROTOCOL_XDDS* pSt_DDSProtocol);
/************************************************************************
函数名称：XDDS_SubScribe_Delete
函数功能：删除一个订阅者
  参数.一：xhSubScribe
   In/Out：In
   类型：网络句柄
   可空：N
   意思：输入要删除的订阅者句柄
返回值
  类型：逻辑型
  意思：是否删除成功
备注：请先删除读者在调用此函数
************************************************************************/
extern "C" BOOL XDDS_SubScribe_Delete(XNETHANDLE xhSubScribe);
/************************************************************************
函数名称：XDDS_SubScribe_ReadMsg
函数功能：为指定读者读取数据
 参数.一：xhSubscribe
  In/Out：In
  类型：网络句柄
  可空：N
  意思：输入要读者所属订阅者
 参数.二：pppSt_MsgBuffer
  In/Out：Out
  类型：三级指针
  可空：N
  意思：输出读取到的缓冲区列表,此参数需要手动释放内存
 参数.三：pInt_ListCount
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出获取到的列表个数
返回值
  类型：逻辑型
  意思：是否读取成功
备注：
************************************************************************/
extern "C" BOOL XDDS_SubScribe_ReadMsg(XNETHANDLE xhSubscribe, DDSSUBSCIRBE_MSGBUFFER * **pppSt_MsgBuffer, int* pInt_ListCount);
