#!/bin/bash
cp -f "../XEngine_BaseLib/libXEngine_BaseLib.so" "./XEngine_Shared/libXEngine_BaseLib.so"
cp -f "../XEngine_BaseLib/libXEngine_Algorithm.so" "./XEngine_Shared/libXEngine_Algorithm.so"
cp -f "../XEngine_Core/libXEngine_Core.so" "./XEngine_Shared/libXEngine_Core.so"
cp -f "../XEngine_Core/libXEngine_ManagePool.so" "./XEngine_Shared/libXEngine_ManagePool.so"
cp -f "../XEngine_HelpComponents/libHelpComponents_Packets.so" "./XEngine_Shared/libHelpComponents_Packets.so"
cp -f "../XEngine_HelpComponents/libHelpComponents_XLog.so" "./XEngine_Shared/libHelpComponents_XLog.so"
cp -f "../XEngine_LinuxApi/libXEngine_ProcSdk.so" "./XEngine_Shared/libXEngine_ProcSdk.so"
cp -f "../XEngine_LinuxApi/libXEngine_LinuxSdk.so" "./XEngine_Shared/libXEngine_LinuxSdk.so"
cp -f "../XEngine_Client/libXClient_Socket.so" "./XEngine_Shared/libXClient_Socket.so"
