#pragma once
/********************************************************************
//	Created:	2019/4/29   9:27
//	Filename: 	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine\NetEngine_WBlackList\WBlackList_Error.h
//	File Path:	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine\NetEngine_WBlackList
//	File Base:	WBlackList_Error
//	File Ext:	h
//  Project:    NetEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	白黑名单列表模块导出错误
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                       IPV4黑名单错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_INIT_PARAMENT 0x20F0001       //参数错误
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_INIT_MALLOC 0x20F0002         //申请内存失败
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ADD_PARAMENT 0x20F0010        //添加失败,参数错误
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ADD_NOTFOUND 0x20F0011        //没有找到指定句柄
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ADD_ISEXIST 0x20F0012         //添加的黑名单已经存在了
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_IPC_ADDRSTART 0x20F0020       //解析开始地址失败
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_IPC_ADDREND 0x20F0021         //解析结束地址失败
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_IPC_NOTSUPPORT 0x20F0022      //不支持的通配符方式
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ISEXIST_ALLNONE 0x20F0030     //全部为过滤,这个设置没有任何效果
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ISEXIST_EXIST 0x20F0031       //已经存在
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ISEXIST_RANGE 0x20F0032       //在范围内
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_GET_PARAMENT 0x20F0040        //参数错误,获取失败
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_GET_NOTFOUND 0x20F0041        //没有找到句柄
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_GET_ISNULL 0x20F0042          //列表为空
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ISEBLACK_PARAMENT 0x20F0050   //参数错误
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ISEBLACK_NOTIPADDR 0x20F0051  //不是标准的IP地址
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ISEBLACK_NOTFOUND 0x20F0052   //没有找到句柄
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ISEBLACK_NOTEXIST 0x20F0053   //这个IP地址不存在
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ADDWHITE_PARAMENT 0x20F0060   //参数错误
#define ERROR_XCORE_WBLACKLIST_IPV4ADDR_ADDWHITE_NOTFOUND 0x20F0061   //没有找到句柄
//////////////////////////////////////////////////////////////////////////
//                       域名黑名单错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_INIT_PARAMENT 0x20F1001     //参数错误
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_INIT_MALLOC 0x20F1002       //申请内存失败
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_ADD_PARAMENT 0x20F1011      //参数错误
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_ADD_NOTFOUND 0x20F1012      //没有找到句柄
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_ADD_ISEXIST 0x20F1013       //已经存在于黑名单
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_GET_PARAMENT 0x20F1020      //参数错误
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_GET_NOTFOUND 0x20F1021      //没有找到句柄
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_GET_ISNULL 0x20F1022        //黑名单列表为空
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_ISEBLACK_PARAMENT 0x20F1030 //参数错误
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_ISEBLACK_NOTFOUND 0x20F1031 //检查失败,没有找到句柄
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_ISEBLACK_NOTEXIST 0x20F1032 //不存在黑名单
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_ADDWHITE_PARAMENT 0x20F1040 //添加失败,参数错误
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_ADDWHITE_NOTFOUND 0x20F1041 //没有找到句柄
#define ERROR_XCORE_WBLACKLIST_DOMAINADDR_CONVERT_NOTDOMAIN 0x20F1050  //这个域名不正确
//////////////////////////////////////////////////////////////////////////
//                       IPV4黑名单错误表
//////////////////////////////////////////////////////////////////////////
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_INIT_PARAMENT 0x20F2001       //参数错误
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_INIT_MALLOC 0x20F2002         //申请内存失败
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ADD_PARAMENT 0x20F2010        //添加失败,参数错误
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ADD_NOTFOUND 0x20F2011        //没有找到指定句柄
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ADD_ISEXIST 0x20F2012         //添加的黑名单已经存在了
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_IPC_ADDRSTART 0x20F2020       //解析开始地址失败
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_IPC_ADDREND 0x20F2021         //解析结束地址失败
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_IPC_NOTSUPPORT 0x20F2022      //不支持的通配符方式
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ISEXIST_ALLNONE 0x20F2030     //全部为过滤,这个设置没有任何效果
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ISEXIST_EXIST 0x20F2031       //已经存在
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ISEXIST_RANGE 0x20F2032       //在范围内
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_GET_PARAMENT 0x20F2040        //参数错误,获取失败
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_GET_NOTFOUND 0x20F2041        //没有找到句柄
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_GET_ISNULL 0x20F2042          //列表为空
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ISEBLACK_PARAMENT 0x20F2050   //参数错误
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ISEBLACK_NOTIPADDR 0x20F2051  //不是标准的IP地址
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ISEBLACK_NOTFOUND 0x20F2052   //没有找到句柄
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ISEBLACK_NOTEXIST 0x20F2053   //这个IP地址不存在
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ADDWHITE_PARAMENT 0x20F2060   //参数错误
#define ERROR_XCORE_WBLACKLIST_IPV6ADDR_ADDWHITE_NOTFOUND 0x20F2061   //没有找到句柄
