#pragma once
/********************************************************************
//	Created:	2019/4/11   15:58
//	Filename: 	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_AvCoder\NetEngine_AVPacket\AVPacket_Define.h
//	File Path:	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_AvCoder\NetEngine_AVPacket
//	File Base:	AVPacket_Define
//	File Ext:	h
//  Project:    NetEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	音视频文件封装模块导出函数
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                      回调函数
//////////////////////////////////////////////////////////////////////////
//读写回调,参数:自定义参数,缓冲区,缓冲区大小
typedef int(*CALLBACK_XENGINE_AVCODEC_AVPACKET_FILEPACKET_FILERW)(XPVOID lParam, uint8_t* puszMsgBuffer, int nSize);
//转换器回调函数,参数:句柄,当前转换帧类型(-1未指定,0VIDEO,1AUDIO)(UNPack表示当前流索引),当前转换帧编号,当前转换时间,自定义参数
typedef void(CALLBACK *CALLBACK_XENGINE_AVCODEC_AVPACKET_NOTIFY)(XHANDLE xhNet, int nCvtType, int nCvtFrame, double dlTime, XPVOID lParam);
//////////////////////////////////////////////////////////////////////////
//                      数据结构
//////////////////////////////////////////////////////////////////////////
typedef struct
{
	XCHAR tszFileName[MAX_PATH];                                           //文件地址,要获取list后设置这个值,写到文件是哪儿,如果是回调,表示写的媒体格式
	double dlAVTime;                                                      //媒体长度
	double dlAVTimeStart;                                                 //提取媒体开始时间,如果不需要设置为0
	double dlAVTimeEnd;                                                   //提取媒体结束时间
	int nAVCodecType;                                                     //媒体类型
	int nAVCodecID;                                                       //媒体ID
	int nAVIndex;                                                         //流索引
	CALLBACK_XENGINE_AVCODEC_AVPACKET_FILEPACKET_FILERW fpCall_Write;     //回调函数,写文件回调,如果为NULL 不通过数据回调
	XPVOID lParam;                                                        //自定义参数
}AVCODEC_PACKETLIST;
//////////////////////////////////////////////////////////////////////////
//                      导出函数声明
//////////////////////////////////////////////////////////////////////////
extern "C" XLONG AVPacket_GetLastError(int *pInt_SysError = NULL);
//////////////////////////////////////////////////////////////////////////
/************************************************************************/
/*                      文件转换器导出函数                              */
/************************************************************************/
/********************************************************************
函数名称：AVPacket_FileConvert_Init
函数功能：初始化一个转换器
 参数.一：pxhNet
  In/Out：Out
  类型：通道句柄
  可空：N
  意思：导出转换器句柄
 参数.二：fpCall_FileConvert
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：转换器过程信息回调
 参数.三：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：句柄型
  意思：成功返回句柄,失败返回NULL
备注：
*********************************************************************/
extern "C" XHANDLE AVPacket_FileConvert_Init(CALLBACK_XENGINE_AVCODEC_AVPACKET_NOTIFY fpCall_FileConvert = NULL, XPVOID lParam = NULL);
/********************************************************************
函数名称：AVPacket_FileConvert_Output
函数功能：输出信息设置
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的转换器
 参数.二：lpszFile
  In/Out：In
  类型：常量字符还真
  可空：Y
  意思：输出的文件路径
 参数.三：dlAVTimeStart
  In/Out：In
  类型：双精度浮点型
  可空：Y
  意思：输入转换后的开始时间,0不设置
 参数.四：dlAVTimeEnd
  In/Out：In
  类型：双精度浮点型
  可空：Y
  意思：输入转换后的结束时间,0不设置
 参数.五：fpCall_AVFile
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：输出到内存而不是文件,此函数不为NULL,参数2表示要转换到的文件格式
 参数.六：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileConvert_Output(XHANDLE xhNet, LPCXSTR lpszFile = NULL, double dlAVTimeStart = 0, double dlAVTimeEnd = 0, CALLBACK_XENGINE_AVCODEC_AVPACKET_FILEPACKET_FILERW fpCall_AVFile = NULL, XPVOID lParam = NULL);
/********************************************************************
函数名称：AVPacket_FileConvert_Input
函数功能：输入要转换的媒体文件
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的转换器
 参数.二：lpszFile
  In/Out：In
  类型：常量字符还真
  可空：Y
  意思：输入要操作的文件路径
 参数.三：pdlAVTime
  In/Out：Out
  类型：浮点型指针
  可空：Y
  意思：输出媒体时间
 参数.四：fpCall_AVFile
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：设置为内存读取文件而不是文件方式
 参数.五：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：逻辑型
  意思：是否成功
备注：先AVPacket_FileConvert_Output 在调用此函数
*********************************************************************/
extern "C" bool AVPacket_FileConvert_Input(XHANDLE xhNet, LPCXSTR lpszFile = NULL, double* pdlAVTime = NULL, CALLBACK_XENGINE_AVCODEC_AVPACKET_FILEPACKET_FILERW fpCall_AVFile = NULL, XPVOID lParam = NULL);
/********************************************************************
函数名称：AVPacket_FileConvert_Start
函数功能：开始转换
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的转换器
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileConvert_Start(XHANDLE xhNet);
/********************************************************************
函数名称：AVPacket_FileConvert_Suspend
函数功能：暂停转换或者继续
 参数.一：xhNet
  In/Out：In
  类型：句柄型
  可空：N
  意思：要操作的句柄
 参数.二：bSuspend
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：真为暂停,假为继续
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileConvert_Suspend(XHANDLE xhNet, bool bSuspend = true);
/********************************************************************
函数名称：AVPacket_FileConvert_GetStatus
函数功能：获取一个转换器的运行状态
 参数.一：xhNet
  In/Out：In
  类型：通道句柄
  可空：N
  意思：要获取的状态的句柄
 参数.二：pbConvert
  In/Out：Out
  类型：逻辑指针
  可空：N
  意思：导出是否完成,反正真表示正在转换,假表示完成
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileConvert_GetStatus(XHANDLE xhNet, bool *pbConvert);
/********************************************************************
函数名称：AVPacket_FileConvert_Stop
函数功能：关闭一个文件格式转换器
 参数.一：xhNet
  In/Out：In
  类型：网络句柄
  可空：N
  意思：要关闭的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：销毁资源必须调用
*********************************************************************/
extern "C" bool AVPacket_FileConvert_Stop(XHANDLE xhNet);
/********************************************************************
函数名称：AVPacket_FileConvert_Seek
函数功能：解码跳转器
 参数.一：xhNet
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：要操作的句柄
 参数.二：nTimePos
  In/Out：In
  类型：整数型
  可空：N
  意思：输入跳转时间
返回值
  类型：逻辑型
  意思：是否成功
备注：快进,快退,定位,使用此函数
*********************************************************************/
extern "C" bool AVPacket_FileConvert_Seek(XHANDLE xhNet, __int64x nTimePos);
/************************************************************************/
/*                      音视频文件封装器导出函数                        */
/************************************************************************/
/********************************************************************
函数名称：AVPacket_FilePacket_Init
函数功能：初始化一个打包器
 参数.一：fpCall_AVNotify
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：打包通知回调
 参数.二：lPararm
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：句柄型
  意思：成功返回句柄,失败返回NULL
备注：
*********************************************************************/
extern "C" XHANDLE AVPacket_FilePacket_Init(CALLBACK_XENGINE_AVCODEC_AVPACKET_NOTIFY fpCall_AVNotify = NULL, XPVOID lPararm = NULL);
/********************************************************************
函数名称：AVPacket_FilePacket_Output
函数功能：打开输出文件信息
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的打包器
 参数.二：lpszFile
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：输入要操作的文件
 参数.三：dlAVTimeStart
  In/Out：In
  类型：双精度浮点型
  可空：Y
  意思：要打包的开始时间,单位秒
 参数.四：dlAVTimeEnd
  In/Out：In
  类型：双精度浮点型
  可空：Y
  意思：要打包的结束时间
 参数.五：fpCall_FileWrite
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：内存会写数据回调,如果不想输出到文件,可以使用此回调
 参数.六：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：逻辑型
  意思：是否成功
备注：如果使用了回调函数,那么第二个参数的意思为输出的格式,比如:flv.mp4
*********************************************************************/
extern "C" bool AVPacket_FilePacket_Output(XHANDLE xhNet, LPCXSTR lpszFile = NULL, double dlAVTimeStart = 0, double dlAVTimeEnd = 0, CALLBACK_XENGINE_AVCODEC_AVPACKET_FILEPACKET_FILERW fpCall_FileWrite = NULL, XPVOID lParam = NULL);
/********************************************************************
函数名称：AVPacket_FilePacket_Input
函数功能：输入要打包的数据信息
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的打包器
 参数.二：lpszFile
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：输入文件路径,也可以是封装好的媒体文件
 参数.三：pdlTime
  In/Out：Out
  类型：浮点型指针
  可空：Y
  意思：输出时长,如果非封包无法获取
 参数.四：fpCall_Read
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：音视频文件读取回调函数(也可以是封装好的媒体文件)
 参数.五：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调自定义参数
返回值
  类型：逻辑型
  意思：是否成功
备注：输入的音频或者视频数据可以采用文件和回调内存方式,但是不能同时使用
      必须先调用AVPacket_FilePacket_Output函数在使用此函数
*********************************************************************/
extern "C" bool AVPacket_FilePacket_Input(XHANDLE xhNet, LPCXSTR lpszFile = NULL, double* pdlTime = NULL, CALLBACK_XENGINE_AVCODEC_AVPACKET_FILEPACKET_FILERW fpCall_Read = NULL, XPVOID lParam = NULL);
/********************************************************************
函数名称：AVPacket_FilePacket_Start
函数功能：开始进行打包
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：要操作的打包器
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FilePacket_Start(XHANDLE xhNet);
/********************************************************************
函数名称：AVPacket_FilePacket_GetStatus
函数功能：获取音视频封包状态
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：要获取的状态的句柄
 参数.二：pbPacket
  In/Out：Out
  类型：逻辑指针
  可空：N
  意思：导出是否完成,真表示正在执行,假表示完成
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FilePacket_GetStatus(XHANDLE xhNet, bool *pbPacket);
/********************************************************************
函数名称：AVPacket_FilePacket_Suspend
函数功能：设置暂停还是继续
 参数.一：xhNet
  In/Out：In
  类型：网络句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：bSuspend
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：为真为暂停,假为继续
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FilePacket_Suspend(XHANDLE xhNet, bool bSuspend = true);
/********************************************************************
函数名称：AVPacket_FilePacket_Stop
函数功能：关闭一个音视频封装器
 参数.一：xhNet
  In/Out：In
  类型：网络句柄
  可空：N
  意思：要关闭的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：销毁资源必须调用
*********************************************************************/
extern "C" bool AVPacket_FilePacket_Stop(XHANDLE xhNet);
/************************************************************************/
/*                      音视频文件解封装器导出函数                      */
/************************************************************************/
/********************************************************************
函数名称：AVPacket_FileUNPack_Init
函数功能：初始化一个文件解封包器
 参数.一：fpCall_AVNotify
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：文件解复用操作进度回调
 参数.二：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：句柄型
  意思：成功返回句柄,失败返回NULL
备注：
*********************************************************************/
extern "C" XHANDLE AVPacket_FileUNPack_Init(CALLBACK_XENGINE_AVCODEC_AVPACKET_NOTIFY fpCall_AVNotify = NULL, XPVOID lParam = NULL);
/********************************************************************
函数名称：AVPacket_FileUNPack_Input
函数功能：设置输入数据流
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：lpszFile
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：要解封包的文件
 参数.三：fpCall_FileRead
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：如果此值不为NULL,表示从内存读取数据
 参数.四：lParam
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileUNPack_Input(XHANDLE xhNet, LPCXSTR lpszFile, CALLBACK_XENGINE_AVCODEC_AVPACKET_FILEPACKET_FILERW fpCall_FileRead = NULL, XPVOID lParam = NULL);
/********************************************************************
函数名称：AVPacket_FileUNPack_GetList
函数功能：获取媒体文件所有流信息
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：输入可操作句柄
 参数.二：pppSt_ListFile
  In/Out：Out
  类型：三级指针
  可空：N
  意思：输出媒体列表
 参数.三：pInt_ListCount
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出列表个数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileUNPack_GetList(XHANDLE xhNet, AVCODEC_PACKETLIST * **pppSt_ListFile, int* pInt_ListCount);
/********************************************************************
函数名称：AVPacket_FileUNPack_Output
函数功能：配置输出数据流
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：pppSt_ListFile
  In/Out：In
  类型：三级指针
  可空：N
  意思：输入文件列表信息
 参数.三：nListCount
  In/Out：In
  类型：整数型
  可空：N
  意思：文件列表个数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileUNPack_Output(XHANDLE xhNet, AVCODEC_PACKETLIST * **pppSt_ListFile, int nListCount);
/********************************************************************
函数名称：AVPacket_FileUNPack_Start
函数功能：开始处理
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：要操作的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileUNPack_Start(XHANDLE xhNet);
/********************************************************************
函数名称：AVPacket_FileUNPack_GetStatus
函数功能：获取音视频解封包状态
 参数.一：xhNet
  In/Out：In
  类型：句柄
  可空：N
  意思：要获取的状态的句柄
 参数.二：pbPacket
  In/Out：Out
  类型：逻辑指针
  可空：N
  意思：导出是否完成,真表示正在执行,假表示完成
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileUNPack_GetStatus(XHANDLE xhNet, bool *pbPacket);
/********************************************************************
函数名称：AVPacket_FileUNPack_Suspend
函数功能：设置暂停还是继续
 参数.一：xhNet
  In/Out：In
  类型：网络句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：bSuspend
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：为真为暂停,假为继续
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileUNPack_Suspend(XHANDLE xhNet, bool bSuspend = true);
/********************************************************************
函数名称：AVPacket_FileUNPack_Stop
函数功能：关闭一个音视频解封装器
 参数.一：xhNet
  In/Out：In
  类型：网络句柄
  可空：N
  意思：要关闭的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：销毁资源必须调用
*********************************************************************/
extern "C" bool AVPacket_FileUNPack_Stop(XHANDLE xhNet);
/************************************************************************/
/*                      媒体文件连接导出函数                            */
/************************************************************************/
/********************************************************************
函数名称：AVPacket_FileLink_Init
函数功能：初始化一个连接器
 参数.一：fpCall_AVNotify
  In/Out：In/Out
  类型：回调函数
  可空：Y
  意思：通知回调
 参数.二：lPararm
  In/Out：In/Out
  类型：无类型指针
  可空：Y
  意思：回调函数自定义参数
返回值
  类型：句柄型
  意思：成功返回句柄,失败返回NULL
备注：
*********************************************************************/
extern "C" XHANDLE AVPacket_FileLink_Init(CALLBACK_XENGINE_AVCODEC_AVPACKET_NOTIFY fpCall_AVNotify = NULL, XPVOID lPararm = NULL);
/********************************************************************
函数名称：AVPacket_FileLink_Output
函数功能：打开输出文件信息
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的打包器
 参数.二：lpszFile
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：输入要操作的文件
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileLink_Output(XHANDLE xhToken, LPCXSTR lpszFile);
/********************************************************************
函数名称：AVPacket_FileLink_Input
函数功能：输入要连接的媒体文件
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的连接器
 参数.二：lpszFile
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入文件路径
 参数.三：dlAVTimeStart
  In/Out：In
  类型：浮点型
  可空：Y
  意思：输入开始时间,为0表示全部
 参数.四：dlAVTimeEnd
  In/Out：In
  类型：浮点型
  可空：Y
  意思：输出结束时间
 参数.五：nVideoIndex
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入要使用的视频索引
 参数.六：nAudioIndex
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入要使用的音频索引
返回值
  类型：逻辑型
  意思：是否成功
备注：需要先调用AVPacket_FileLink_Output在调用AVPacket_FileLink_Input
*********************************************************************/
extern "C" bool AVPacket_FileLink_Input(XHANDLE xhToken, LPCXSTR lpszFile, double dlAVTimeStart = 0, double dlAVTimeEnd = 0, int nVideoIndex = -1, int nAudioIndex = -1);
/********************************************************************
函数名称：AVPacket_FileLink_Start
函数功能：开始进行连接
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：要操作的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileLink_Start(XHANDLE xhToken);
/********************************************************************
函数名称：AVPacket_FileLink_GetStatus
函数功能：获取媒体连接状态
 参数.一：xhToken
  In/Out：In
  类型：句柄
  可空：N
  意思：要获取的句柄
 参数.二：pbPacket
  In/Out：Out
  类型：逻辑指针
  可空：N
  意思：导出是否完成,真表示正在执行,假表示完成
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileLink_GetStatus(XHANDLE xhToken, bool* pbLink);
/********************************************************************
函数名称：AVPacket_FileLink_Suspend
函数功能：设置暂停还是继续
 参数.一：xhToken
  In/Out：In
  类型：网络句柄
  可空：N
  意思：输入要操作的句柄
 参数.二：bSuspend
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：为真为暂停,假为继续
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool AVPacket_FileLink_Suspend(XHANDLE xhToken, bool bSuspend = true);
/********************************************************************
函数名称：AVPacket_FileLink_Stop
函数功能：关闭一个连接器
 参数.一：xhToken
  In/Out：In
  类型：网络句柄
  可空：N
  意思：要关闭的句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：销毁资源必须调用
*********************************************************************/
extern "C" bool AVPacket_FileLink_Stop(XHANDLE xhToken);