#pragma once
/********************************************************************
//    Created:     2020/12/23  20:54:00
//    File Name:   H:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_XMQCore\MQCore_XMQService\XMQService_Define.h
//    File Path:   H:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_XMQCore\MQCore_XMQService
//    File Base:   XMQService_Define
//    File Ext:    h
//    Project:     XEngine(网络通信引擎)
//    Author:      qyt
//    Purpose:     消息队列导出定义
//    History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                       导出的数据结构
//////////////////////////////////////////////////////////////////////////
typedef struct
{
    XENGINE_PROTOCOL_USERAUTH st_AuthProtocol;                          //用户信息
    time_t nStartTime;                                                    //进入时间
    int nSerial;                                                          //数据消息序列
}XENGINE_MQ_USERINFO, * LPXENGINE_MQ_USERINFO;
//////////////////////////////////////////////////////////////////////////
//                       导出的函数
//////////////////////////////////////////////////////////////////////////
extern "C" DWORD XMQService_GetLastError(int *pInt_SysError = NULL);
/*************************************************************************
                        消息队列包管理导出函数
**************************************************************************/
/************************************************************************
函数名称：XMQService_Packet_Init
函数功能：初始化消息队列包管理工具
  参数.一：nMaxPacket
   In/Out：In
   类型：整数型
   可空：Y
   意思：最大允许消息队列保存个数
返回值
  类型：逻辑型
  意思：是否初始化成功
备注：
************************************************************************/
extern "C" BOOL XMQService_Packet_Init(int nMaxPacket = 10000);
/************************************************************************
函数名称：XMQService_Packet_Destory
函数功能：销毁消息队列包管理工具
返回值
  类型：逻辑型
  意思：是否销毁成功
备注：
************************************************************************/
extern "C" BOOL XMQService_Packet_Destory();
/************************************************************************
函数名称：XMQService_Packet_Post
函数功能：投递一个数据包到消息队列中
  参数.一：pSt_ProtocolHdr
   In/Out：In
   类型：数据结构指针
   可空：N
   意思：输入协议头数据
  参数.二：lpszMsgBuffer
   In/Out：In
   类型：常量字符指针
   可空：N
   意思：要投递的BUFF缓冲区
返回值
  类型：逻辑型
  意思：是否投递成功
备注：
************************************************************************/
extern "C" BOOL XMQService_Packet_Post(XENGINE_PROTOCOLHDR *pSt_ProtocolHdr,LPCSTR lpszMsgBuffer);
/************************************************************************
函数名称：XMQService_Packet_Get
函数功能：从一个消息队列中获取一个包
  参数.一：pSt_ProtocolHdr
   In/Out：In
   类型：数据结构指针
   可空：N
   意思：数据协议头
  参数.二：lpszMsgBuffer
   In/Out：In
   类型：常量字符指针
   可空：N
   意思：输入后续数据长度
  参数.三：ptszMsgBuffer
   In/Out：Out
   类型：字符指针
   可空：N
   意思：导出获取到的数据
  参数.四：pInt_Len
   In/Out：In/Out
   类型：整数型指针
   可空：N
   意思：输入，获取数据缓冲区大小，输出真实获取到的大小
  参数.五：pInt_Serial
   In/Out：In/Out
   类型：整数型指针
   可空：Y
   意思：输入，缓存的序列号，输出最新序列号,这个功能只对bSerial为真有效
返回值
  类型：逻辑型
  意思：是否获取成功
备注：
************************************************************************/
extern "C" BOOL XMQService_Packet_Get(XENGINE_PROTOCOLHDR *pSt_ProtocolHdr,LPCSTR lpszMsgBuffer,CHAR *ptszMsgBuffer,int *pInt_Len, int* pInt_Serial = NULL);
/************************************************************************
函数名称：XMQService_Packet_Del
函数功能：从一个队列中删除一个包
  参数.一：pSt_ProtocolHdr
   In/Out：In
   类型：数据结构指针
   可空：N
   意思：要删除的数据协议头信息
  参数.二：lpszMsgBuffer
   In/Out：In
   类型：常量字符指针
   可空：N
   意思：附加删除协议数据
返回值
  类型：逻辑型
  意思：是否删除成功
备注：
************************************************************************/
extern "C" BOOL XMQService_Packet_Del(XENGINE_PROTOCOLHDR *pSt_ProtocolHdr,LPCSTR lpszMsgBuffer);
/*************************************************************************
                        协议处理管理导出函数
**************************************************************************/
/********************************************************************
函数名称：XMQService_Protocol_PostPacket
函数功能：封装投递消息队列协议包
 参数.一：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：导出封装号的协议
 参数.二：pInt_Len
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：导出封装的协议的长度
 参数.三：unOperatorCode
  In/Out：In
  类型：整数型
  可空：N
  意思：输入消息队列子协议
 参数.四：pSt_XMQProtocol
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入要投递的参数信息
 参数.五：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：要封装的数据
 参数.六：nMsgLen
  In/Out：In
  类型：整数型
  可空：Y
  意思：要封装数据的长度
 参数.七：nPkgSerial
  In/Out：In
  类型：整数型
  可空：Y
  意思：投递包的序列号，0不启用，最大为65535，如果你设置了 KeepTime = -1 那么这个序列号不能重复使用
 参数.八：bIsReply
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否需要回复包，投递成功与否都会返回一个协议头
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XMQService_Protocol_REQPacket(CHAR * ptszMsgBuffer, int* pInt_Len, UINT unOperatorCode, XENGINE_PROTOCOL_XMQ * pSt_XMQProtocol, LPCSTR lpszMsgBuffer = NULL, int nMsgLen = 0, int nPkgSerial = 0, BOOL bIsReply = TRUE);
/********************************************************************
函数名称：XMQService_Protocol_REPPacket
函数功能：封装投递消息队列协议包
 参数.一：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：导出封装号的协议
 参数.二：pInt_Len
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：导出封装的协议的长度
 参数.三：unOperatorCode
  In/Out：In
  类型：整数型
  可空：N
  意思：输入消息队列子协议
 参数.四：wResver
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入处理结果
 参数.五：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：要封装的数据
 参数.六：nMsgLen
  In/Out：In
  类型：整数型
  可空：Y
  意思：要封装数据的长度
 参数.七：nPkgSerial
  In/Out：In
  类型：整数型
  可空：Y
  意思：投递包的序列号，0不启用，最大为65535，如果你设置了 KeepTime = -1 那么这个序列号不能重复使用
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XMQService_Protocol_REPPacket(CHAR* ptszMsgBuffer, int* pInt_Len, UINT unOperatorCode, WORD wResver = 0, LPCSTR lpszMsgBuffer = NULL, int nMsgLen = 0, int nPkgSerial = 0);
/********************************************************************
函数名称：XMQService_Protocol_Login
函数功能：打包登录请求
 参数.一：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打好包的数据缓冲区
 参数.二：pInt_Len
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出缓冲区大小
 参数.三：pSt_UserAuth
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入用户验证信息
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XMQService_Protocol_REQLogin(CHAR* ptszMsgBuffer, int* pInt_Len, XENGINE_PROTOCOL_USERAUTH* pSt_UserAuth);
/********************************************************************
函数名称：XMQService_Protocol_REPLogin
函数功能：回复登录请求
 参数.一：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打好包的登录协议回复处理结果包
 参数.二：pInt_Len
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出包大小
 参数.二：wCode
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入处理结果
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XMQService_Protocol_REPLogin(CHAR* ptszMsgBuffer, int* pInt_Len, WORD wCode = 0);
/*************************************************************************
                        用户处理管理导出函数
**************************************************************************/
/********************************************************************
函数名称：XMQService_User_Insert
函数功能：插入一个用户到管理器中
 参数.一：lpszClientAddr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入用户关联的连接地址
 参数.二：pSt_UserAuth
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入要插入的用户信息
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XMQService_User_Insert(LPCSTR lpszClientAddr, XENGINE_PROTOCOL_USERAUTH* pSt_UserAuth);
/********************************************************************
函数名称：XMQService_User_GetSerial
函数功能：获取用户当前序列
 参数.一：lpszClientAddr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入用户地址
 参数.二：pSt_UserInfo
  In/Out：Out
  类型：数据结构指针
  可空：N
  意思：输出用户信息
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XMQService_User_GetInfo(LPCSTR lpszClientAddr, XENGINE_MQ_USERINFO * pSt_UserInfo);
/********************************************************************
函数名称：XMQService_User_SetSerial
函数功能：设置序列号
 参数.一：lpszClientAddr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要删除的用户地址
 参数.二：nSerial
  In/Out：In
  类型：整数型
  可空：N
  意思：输入要设置的序列号
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XMQService_User_SetSerial(LPCSTR lpszClientAddr, int nSerial);
/********************************************************************
函数名称：XMQService_User_Delete
函数功能：删除用户
 参数.一：lpszClientAddr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要删除的用户地址
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" BOOL XMQService_User_Delete(LPCSTR lpszClientAddr);
