#pragma once
/********************************************************************
//	Created:	2012/1/21  18:10
//	File Name: 	J:\U_DISK_Path\NetSocketEngine\NetEngine_DownLoad\NetEngine_DownLoad\DownLoad_Error.h
//	File Path:	J:\U_DISK_Path\NetSocketEngine\NetEngine_DownLoad\NetEngine_DownLoad
//	File Base:	DownLoad_Error
//	File Ext:	h
//  Project:    NetSocketEngine(网络通信引擎)
//	Author:		Dowflyon
//	Purpose:	网络下载引擎，错误导出表
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
//                       HTTP下载错误,需要NetEngine_PublicOperatorSting 的支持
//////////////////////////////////////////////////////////////////////////
#define ERROR_XENGINE_DOWNLOAD_HTTP_CREATE_PARAMENT 0x060A0001          //创建HTTP下载参数错误
#define ERROR_XENGINE_DOWNLOAD_HTTP_CREATE_MALLOC 0x060A0002            //申请空间失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_CREATE_INIT 0x060A0003              //初始化下载引擎失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_CREATE_PARAMENTISTOOLONG 0x060A0004 //参数传递的太上了，无法继续
#define ERROR_XENGINE_DOWNLOAD_HTTP_CREATE_FILEEXIST 0xBBF0005          //指定的保存文件路径已经有文件存在
#define ERROR_XENGINE_DOWNLOAD_HTTP_CREATE_CREATETHREAD 0x060A0006      //创建下载线程失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_QUERY_NOTSUPPORT 0x060A0010         //查询失败，不支持此查询方式，你需要使用回调
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_URLADDR 0x060A1030        //设置下载地址失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_CONNTIMEDOUT 0x060A1031   //设置连接超时失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_RWTIMEDOUT 0x060A1032     //设置读写超时失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_WRITEFUNC 0x060A1033      //设置写操作函数失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_WRITEPARAMENT 0x060A1034  //设置写操作函数参数失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_SETPROGRESS 0x060A1035    //设置过程失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_PROGRESSFUNC 0x060A1036   //设置过程函数失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_PROGRESSPARAMENT 0x060A1037//设置过程函数参数失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETOPTION_SETRANGE 0x060A1038       //设置文件写入位置失败，文件续传出现错误
#define ERROR_XENGINE_DOWNLOAD_HTTP_GETFILE_WRITEOPEN 0x060A1041        //打开失败，可能权限有问题
#define ERROR_XENGINE_DOWNLOAD_HTTP_GETFILE_OPENREAD 0x060A1042         //打开追加文件失败，内部错误
#define ERROR_XENGINE_DOWNLOAD_HTTP_GETFILE_SEEKPOS 0x060A1043          //移动文件指针失败，无法继续，续传出错
#define ERROR_XENGINE_DOWNLOAD_HTTP_PAUSE_NOTFOUND 0x060A1050           //暂停失败，没有找到任务
#define ERROR_XENGINE_DOWNLOAD_HTTP_PAUSE_NOTDOWNLOADING 0x060A1051     //暂停失败，找到任务，但是任务没有下载
#define ERROR_XENGINE_DOWNLOAD_HTTP_PAUSE_ISSUSPENDED 0x060A1052        //暂停失败，任务已经是暂停中
#define ERROR_XENGINE_DOWNLOAD_HTTP_PAUSE_PAUSEALL 0x060A1053           //暂停下载失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_PAUSE_ISDOWNLOADING 0x060A1054      //已经在下载中，无法恢复下载
#define ERROR_XENGINE_DOWNLOAD_HTTP_PAUSE_NOTSUSPENDED 0x060A1054       //不是暂停状态，状态错误，无法恢复
#define ERROR_XENGINE_DOWNLOAD_HTTP_PAUSE_UNPAUSEALL 0x060A1055         //恢复下载失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_GET_FILESIZE_PARAMENT 0x060A1060    //参数错误
#define ERROR_XENGINE_DOWNLOAD_HTTP_GET_FILESIZE_INIT 0x060A1061        //初始化化失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_GET_FILESIZE_SETURL 0x060A1062      //设置URL失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_GET_FILESIZE_NOTHEADER 0x060A1063   //设置头失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_GET_FILESIZE_NOTBODY 0x060A1064     //设置内容失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_GET_FILESIZE_EXEC 0x060A1065        //执行失败，内部错误
#define ERROR_XENGINE_DOWNLOAD_HTTP_GET_FILESIZE_LENGTH 0x060A1066      //获取长度失败，内部错误
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETSPEED_NOTFOUND 0x060A1070        //设置速度失败，没有找到任务
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETSPEED_MAXRECV 0x060A1071         //设置最大接受速度失败
#define ERROR_XENGINE_DOWNLOAD_HTTP_SETSPEED_MAXRSEND 0x060A1072        //设置最大发送速度失败
//////////////////////////////////////////////////////////////////////////
//                       ftp下载错误,需要NetEngine_PublicOperatorSting 的支持
//////////////////////////////////////////////////////////////////////////
#define ERROR_XENGINE_DOWNLOAD_FTP_CREATE_PARAMENT 0x060A1001           //创建HTTP下载参数错误
#define ERROR_XENGINE_DOWNLOAD_FTP_CREATE_MALLOC 0x060A1002             //申请空间失败
#define ERROR_XENGINE_DOWNLOAD_FTP_CREATE_INIT 0x060A1003               //初始化下载引擎失败
#define ERROR_XENGINE_DOWNLOAD_FTP_CREATE_PARAMENTISTOOLONG 0x060A1004  //参数传递的太上了，无法继续
#define ERROR_XENGINE_DOWNLOAD_FTP_CREATE_CREATETHREAD 0x060A1005       //创建下载线程失败
#define ERROR_XENGINE_DOWNLOAD_FTP_QUERY_NOTSUPPORT 0x060A1010          //查询失败，不支持此查询方式，你需要使用回调
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_URLADDR 0x060A1030         //设置下载或者上传地址失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_CONNTIMEDOUT 0x060A1031    //连接超时设定失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_RESPONSE_TIMEOUT 0x060A1A32//响应超时时间
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_RWTIMEDOUT 0x060A1032      //传输超时设定失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_PASV 0x060A1034            //设置PASV传输模式失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_WRITEFUNC 0x060A1035       //设置写函数失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_WRITEPARAMENT 0x060A1036   //设置写函数参数失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_SETPUT 0x060A1037          //设置上传模式失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_UPFILE 0x060A1038          //设置上传文件失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_SETSIZE 0x060A1039         //设置上传文件大小失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_REDFUNC 0x060A103A         //读取函数设置失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_MISSIONDIR 0x060A103B      //跳过文件夹设置失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_READDATA 0x060A103C        //读取函数数据失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_SETPROGRESS 0x060A103D     //设置过程失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_PROGRESSFUNC 0x060A103E    //设置过程函数失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_PROGRESSPARAMENT 0x060A103F//设置过程函数参数失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETOPTION_SETRANGE 0x060A1A3F        //设置下载起始地址失败
#define ERROR_XENGINE_DOWNLOAD_FTP_GETFILE_SIZE 0x060A1040              //获取文件大小失败
#define ERROR_XENGINE_DOWNLOAD_FTP_GETFILE_NOTFOUND 0x060A1041          //文件不存在
#define ERROR_XENGINE_DOWNLOAD_FTP_GETFILE_WRITEOPEN 0x060A1042         //写入文件打开失败，请检查文件是否有权限写
#define ERROR_XENGINE_DOWNLOAD_FTP_GETFILE_READOPEN 0x060A1043          //读取文件打开失败，请检查文件是否有权限读
#define ERROR_XENGINE_DOWNLOAD_FTP_GETFILE_SEEKPOS 0x060A1044           //移动指针失败
#define ERROR_XENGINE_DOWNLOAD_FTP_PAUSE_NOTFOUND 0x060A1050            //没有找到无法继续
#define ERROR_XENGINE_DOWNLOAD_FTP_PAUSE_NOTDOWNLOADING 0x060A1051      //没有下载中，无法继续
#define ERROR_XENGINE_DOWNLOAD_FTP_PAUSE_ISSUSPENDED 0x060A1052         //已经是暂停状态，无法继续
#define ERROR_XENGINE_DOWNLOAD_FTP_PAUSE_PAUSEALL 0x060A1053            //暂停失败
#define ERROR_XENGINE_DOWNLOAD_FTP_PAUSE_ISDOWNLOADING 0x060A1054       //已经在运行，无法继续
#define ERROR_XENGINE_DOWNLOAD_FTP_PAUSE_NOTSUSPENDED 0x060A1055        //不是暂停状态，无法恢复
#define ERROR_XENGINE_DOWNLOAD_FTP_PAUSE_UNPAUSEALL 0x060A1056          //恢复下载失败
#define ERROR_XENGINE_DOWNLOAD_FTP_REMOTEFEXIST_PARAMENT 0x060A1060     //参数错误
#define ERROR_XENGINE_DOWNLOAD_FTP_REMOTEFEXIST_INIT 0x060A1061         //初始化错误
#define ERROR_XENGINE_DOWNLOAD_FTP_REMOTEFEXIST_NOBODY 0x060A1062       //数据取回设置失败
#define ERROR_XENGINE_DOWNLOAD_FTP_REMOTEFEXIST_EXEC 0x060A1063         //执行失败
#define ERROR_XENGINE_DOWNLOAD_FTP_REMOTEFEXIST_NOTFOUND 0x060A1064     //没有找到文件，可能文件不存在
#define ERROR_XENGINE_DOWNLOAD_FTP_SETSPEED_NOTFOUND 0x060A1070         //设置速度失败，没有找到任务
#define ERROR_XENGINE_DOWNLOAD_FTP_SETSPEED_MAXRECV 0x060A1071          //设置最大接受速度失败
#define ERROR_XENGINE_DOWNLOAD_FTP_SETSPEED_MAXRSEND 0x060A1072         //设置最大发送速度失败
