#pragma once
/********************************************************************
//    Created:     2023/05/15  14:21:00
//    File Name:   D:\XEngine\XEngine_SourceCode\XEngine_StreamMedia\StreamMedia_FLVProtocol\FLVProtocol_Define.h
//    File Path:   D:\XEngine\XEngine_SourceCode\XEngine_StreamMedia\StreamMedia_FLVProtocol
//    File Base:   FLVProtocol_Define
//    File Ext:    h
//    Project:     XEngine(网络通信引擎)
//    Author:      qyt
//    Purpose:     FLV协议模块定义
//    History:
*********************************************************************/
typedef struct
{
	XBYTE byType;                  //类型,2为字符串,1为逻辑型,0为double
	XSHOT nMLen;                   //大小
	XCHAR tszKeyStr[MAX_PATH];
	XCHAR tszVluStr[MAX_PATH];
}XENGINE_FLVAVINFO;
//视频标签,5个字节
typedef struct
{
	XBYTE byCodecID : 4;        //编码器ID,7;h264,12:h265
	XBYTE byFrameType : 4;      //帧类型:1关键帧,2其他

	XBYTE byAVCType;            //AVC帧类型,0,AVC sequence header,1 avc nalu,2avc end of sequence 
	XBYTE byCompositionTime[3]; //PTS和DTS的时间偏移值,单位毫秒,记作cts,若含 B 帧，则 PTS 和 DTS 不同，H264 视频帧 PTS = DTS + CTS
}XENGINE_FLVVIDEO;
//音频标签,2个字节
typedef struct
{
	XBYTE byAudioType : 1;  //0 - mono, 1 - stereo
	XBYTE byAudioSize : 1;  //0 - 8 bit, 1 - 16 bit
	XBYTE byAudioRate : 2;  //0 - 5.5 KHz, 1 - 11 KHz, 2 - 22 KHz, 3 - 44 KHz
	XBYTE byAudioFmt : 4;   //0 - raw, 1 - ADPCM, 2 - MP3, 4 - Nellymoser 16 KHz mono, 5 - Nellymoser 8 KHz mono, 10 - AAC, 11 - Speex

	XBYTE byPKTType;        //仅仅当AAC生效,0,aac sequence header,1 aac raw
}XENGINE_FLVAUDIO;
///////////////////////////////////////////////////////////////////////////////
//                               导出的函数
///////////////////////////////////////////////////////////////////////////////
extern "C" XLONG FLVProtocol_GetLastError(int *pInt_SysError = NULL);
/******************************************************************************
                             FLV解析器导出函数
******************************************************************************/
/********************************************************************
函数名称：FLVProtocol_Parse_Init
函数功能：初始化FLV解析器
 参数.一：nPoolCount
  In/Out：In
  类型：整数型
  可空：N
  意思：输入允许的任务池队列个数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_Init(int nPoolCount);
/********************************************************************
函数名称：FLVProtocol_Parse_Destory
函数功能：销毁FLV解析器
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_Destory();
/********************************************************************
函数名称：FLVProtocol_Parse_Insert
函数功能：插入一个客户端到FLV解析器
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要插入的客户端ID
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_Insert(LPCXSTR lpszClientID);
/********************************************************************
函数名称：FLVProtocol_Parse_Delete
函数功能：从解析器中删除一个客户端
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_Delete(LPCXSTR lpszClientID);
/********************************************************************
函数名称：FLVProtocol_Parse_Send
函数功能：发送一段flv数据给解析器
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要解析的数据
 参数.三：nMsgLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入要解析的数据大小
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_Send(LPCXSTR lpszClientID, LPCXSTR lpszMsgBuffer, int nMsgLen);
/********************************************************************
函数名称：FLVProtocol_Parse_Recv
函数功能：获得解析好的数据
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：pptszMsgBuffer
  In/Out：Out
  类型：指向指针的指针
  可空：N
  意思：输出获取到的负载编码数据,此内存需要用户手动释放
 参数.三：pInt_MsgLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出编码数据大小
 参数.四：pInt_AVType
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出媒体类型,0视频,1音频
 参数.五：pSt_FLVVideo
  In/Out：Out
  类型：数据结构指针
  可空：Y
  意思：视频类型存在,表示视频信息
 参数.六：pSt_FLVAudio
  In/Out：Out
  类型：数据结构指针
  可空：Y
  意思：音频类型存在,表示音频信息
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_Recv(LPCXSTR lpszClientID, XCHAR * *pptszMsgBuffer, int* pInt_MsgLen, int* pInt_AVType, XENGINE_FLVVIDEO * pSt_FLVVideo = NULL, XENGINE_FLVAUDIO * pSt_FLVAudio = NULL);
/********************************************************************
函数名称：FLVProtocol_Parse_GetMetaInfo
函数功能：获取媒体信息
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：ptszSPSBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出媒体的SPS信息
 参数.三：ptszPPSBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出媒体的PPS信息
 参数.四：pInt_SPSLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出SPS大小
 参数.五：pInt_PPSLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出PPS大小
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_GetMetaInfo(LPCXSTR lpszClientID, XCHAR* ptszSPSBuffer, XCHAR* ptszPPSBuffer, int* pInt_SPSLen, int* pInt_PPSLen);
/********************************************************************
函数名称：FLVProtocol_Parse_GetScriptInfo
函数功能：获取FLV扩展的音视频信息
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：pppSt_FLVInfoList
  In/Out：Out
  类型：三级指针
  可空：N
  意思：输出获取到的信息列表(内存需要释放)
 参数.三：pInt_ListCount
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出列表个数
返回值
  类型：逻辑型
  意思：是否成功
备注：Script标签信息
*********************************************************************/
extern "C" bool FLVProtocol_Parse_GetScriptInfo(LPCXSTR lpszClientID, XENGINE_FLVAVINFO*** pppSt_FLVInfoList, int* pInt_ListCount);
/********************************************************************
函数名称：FLVProtocol_Parse_GetPool
函数功能：通过任务池获取可处理的列表
 参数.一：nPoolIndex
  In/Out：In
  类型：整数型
  可空：N
  意思：输入要处理的索引
 参数.二：pppSt_ListAddr
  In/Out：Out
  类型：三级指针
  可空：N
  意思：导出待处理的列表
 参数.三：pInt_ListCount
  In/Out：Out
  类型：指数型指针
  可空：N
  意思：导出列表的个数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_GetPool(int nPoolIndex, XENGINE_MANAGEPOOL_TASKEVENT*** pppSt_ListAddr, int* pInt_ListCount);
/************************************************************************
函数名称：FLVProtocol_Parse_WaitEvent
函数功能：等待一个数据事件发生
 参数.一：nPoolIndex
  In/Out：In
  类型：整数型
  可空：Y
  意思：分布式池索引
 参数.二：nTimeOut
  In/Out：In
  类型：整数型
  可空：Y
  意思：超时时间,单位毫秒 -1 不超时,0立即返回 > 0等待事件
返回值
  类型：逻辑型
  意思：是否等待成功
备注：
************************************************************************/
extern "C" bool FLVProtocol_Parse_WaitEvent(int nPoolIndex, int nTimeOut = -1);
/********************************************************************
函数名称：FLVProtocol_Parse_ActiveEvent
函数功能：手动触发一次事件
 参数.一：nPoolIndex
  In/Out：In
  类型：整数型
  可空：Y
  意思：分布池索引
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Parse_ActiveEvent(int nPoolIndex);
/******************************************************************************
							 FLV打包器导出函数
******************************************************************************/
/********************************************************************
函数名称：FLVProtocol_Packet_Insert
函数功能：插入一个客户端到FLV封包器中
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：bVideo
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否启用视频
 参数.三：bAudio
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：是否启用音频
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Packet_Insert(LPCXSTR lpszClientID, bool bVideo = true, bool bAudio = true);
/********************************************************************
函数名称：FLVProtocol_Packet_Delete
函数功能：删除一个客户端从封包器中
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Packet_Delete(LPCXSTR lpszClientID);
/********************************************************************
函数名称：FLVProtocol_Packet_SetTime
函数功能：设置时间戳
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：nVideoFrame
  In/Out：In
  类型：整数型
  可空：N
  意思：输入H264帧率
 参数.三：nAudioFrame
  In/Out：In
  类型：整数型
  可空：N
  意思：输入AAC音频采样率
返回值
  类型：逻辑型
  意思：是否成功
备注：仅适用于H264和AAC常规时间戳增量.时间戳为0将采用设置的参数计算
*********************************************************************/
extern "C" bool FLVProtocol_Packet_SetTime(LPCXSTR lpszClientID, int nVideoFrame, int nAudioFrame);
/********************************************************************
函数名称：FLVProtocol_Packet_FrameHdr
函数功能：打包FLV头
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打包的数据
 参数.三：pInt_MsgLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出数据大小
返回值
  类型：逻辑型
  意思：是否成功
备注：1.先打包FLV头
*********************************************************************/
extern "C" bool FLVProtocol_Packet_FrameHdr(LPCXSTR lpszClientID, XCHAR * ptszMsgBuffer, int* pInt_MsgLen);
/********************************************************************
函数名称：FLVProtocol_Packet_FrameScript
函数功能：打包脚本标签数据
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打包的数据
 参数.三：pInt_MsgLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出数据大小
 参数.四：pSt_AVInfo
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入要打包的信息,要设置音频或者视频,你需要填充相应的内容
返回值
  类型：逻辑型
  意思：是否成功
备注：2.在打包脚本TAG
*********************************************************************/
extern "C" bool FLVProtocol_Packet_FrameScript(LPCXSTR lpszClientID, XCHAR * ptszMsgBuffer, int* pInt_MsgLen, XENGINE_PROTOCOL_AVINFO * pSt_AVInfo);
/********************************************************************
函数名称：FLVProtocol_Packet_FrameAVCConfigure
函数功能：打包H264视频参数配置信息
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打包的数据
 参数.三：pInt_MsgLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出数据大小
 参数.四：pSt_AVInfo
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入要打包的信息,视频数据结构必须填充SPS和PPS信息
返回值
  类型：逻辑型
  意思：是否成功
备注：3.在打包视频参数信息
*********************************************************************/
extern "C" bool FLVProtocol_Packet_FrameAVCConfigure(LPCXSTR lpszClientID, XCHAR * ptszMsgBuffer, int* pInt_MsgLen, XENGINE_PROTOCOL_AVINFO * pSt_AVInfo);
/********************************************************************
函数名称：FLVProtocol_Packet_FrameAACConfigure
函数功能：打包AAC音频参数配置信息
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打包的数据
 参数.三：pInt_MsgLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出数据大小
 参数.四：pSt_AVInfo
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入要打包的信息,音频数据需要输入相应的参数,AAC的数据必须填充到音频缓冲区
返回值
  类型：逻辑型
  意思：是否成功
备注：3.如果需要打包音频,也可以设置此参数
*********************************************************************/
extern "C" bool FLVProtocol_Packet_FrameAACConfigure(LPCXSTR lpszClientID, XCHAR * ptszMsgBuffer, int* pInt_MsgLen, XENGINE_PROTOCOL_AVINFO * pSt_AVInfo);
/********************************************************************
函数名称：FLVProtocol_Packet_FrameCustom
函数功能：打包自定义帧负载数据
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打包的数据
 参数.三：pInt_MsgLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出数据大小
 参数.四：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要打包的数据
 参数.五：nMsgLen
  In/Out：In
  类型：整数型
  可空：N
  意思：输入打包数据大小
 参数.六：nTimestamp
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入当前包的时间戳,默认采用设置的时间戳自增
 参数.七：nTagType
  In/Out：In
  类型：整数型
  可空：N
  意思：输入打包数据类型,8 AUDIO,9 VIDEO,18 SCRIPT
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool FLVProtocol_Packet_FrameCustom(LPCXSTR lpszClientID, XCHAR * ptszMsgBuffer, int* pInt_MsgLen, LPCXSTR lpszMsgBuffer, int nMsgLen, int nTimestamp = -1, int nTagType = 9);
/********************************************************************
函数名称：FLVProtocol_Packet_FrameVideo
函数功能：打包一帧视频数据
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打包的数据
 参数.三：pInt_MsgLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出数据大小
 参数.四：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：输入要打包的数据,需要一个完整的NAL,不支持拆分包
 参数.五：nMsgLen
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入要打包的数据的大小
 参数.六：nTimestamp
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入时间戳,0为系统自动计算
 参数.七：nFrameType
  In/Out：In
  类型：整数型
  可空：Y
  意思：帧类型,1为关键帧,否则为其他帧
返回值
  类型：逻辑型
  意思：是否成功
备注：4.打包视频数据,视频数据开头必须是00 00 00 01(00 00 01)的完整NAL
*********************************************************************/
extern "C" bool FLVProtocol_Packet_FrameVideo(LPCXSTR lpszClientID, XCHAR * ptszMsgBuffer, int* pInt_MsgLen, LPCXSTR lpszMsgBuffer = NULL, int nMsgLen = 0, int nTimestamp = -1, int nFrameType = 0);
/********************************************************************
函数名称：FLVProtocol_Packet_FrameAudio
函数功能：打包一帧音频数据
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要操作的客户端ID
 参数.二：ptszMsgBuffer
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出打包的数据
 参数.三：pInt_MsgLen
  In/Out：Out
  类型：整数型指针
  可空：N
  意思：输出数据大小
 参数.四：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：输入要打包的数据,需要一个完整的AAC包,不支持拆分包
 参数.五：nMsgLen
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入要打包的数据的大小
 参数.六：nTimestamp
  In/Out：In
  类型：整数型
  可空：Y
  意思：输入时间戳
返回值
  类型：逻辑型
  意思：是否成功
备注：4.打包音频数据
*********************************************************************/
extern "C" bool FLVProtocol_Packet_FrameAudio(LPCXSTR lpszClientID, XCHAR * ptszMsgBuffer, int* pInt_MsgLen, LPCXSTR lpszMsgBuffer = NULL, int nMsgLen = 0, int nTimestamp = -1);