#pragma once
/********************************************************************
//	Created:	2019/8/21   15:53
//	Filename: 	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_StreamMedia\StreamMedia_RtspProtocol\RTSPProtocol_Error.h
//	File Path:	E:\NetEngine_Windows\NetEngine_SourceCode\NetEngine_StreamMedia\StreamMedia_RtspProtocol
//	File Base:	RTSPProtocol_Error
//	File Ext:	h
//  Project:    NetEngine(网络通信引擎)
//	Author:		qyt
//	Purpose:	RTSP协议处理模块导出错误
//	History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
///                           RTSP服务核心相关错误码
//////////////////////////////////////////////////////////////////////////
/************************************************************************/
/*                            RTSP协议包管理错误导出                    */
/************************************************************************/
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_CREATE_PARAMENT 0x90D0001       //创建失败,参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_INSERT_PARAMENT 0x90D0010       //插入失败,参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_INSERT_NOTFOUND 0x90D0011       //没有找到指定客户端
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_GET_PARAMENT 0x90D0020          //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_GET_NOTFOUND 0x90D0021          //没有找到
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_GET_EMPTY 0x90D0022             //队列为空
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSEINFO_PARAMENT 0x90D0030    //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSEINFO_NOURL 0x90D0031       //没有URL信息
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSEINFO_NOSEQ 0x90D0032       //没有SEQ序列号
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_CVT_PARAMENT 0x90D0040          //转换失败,参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_CVT_NOTSUPPORT 0x90D0041        //不支持的方法
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_AUTH_BUFFER 0x90D0050           //验证缓冲区解析失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_AUTH_USER 0x90D0051             //解析用户密码失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_AUTH_NOTSUPPORT 0x90D0052       //不支持的验证方式
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETMETHOD 0x90D00A1       //获取方法失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETURL 0x90D0A2           //获取URL失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETVERSION 0x90D00A3      //获取版本失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETSEQ 0x90D00A4          //获取SEQ序列号字段失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETCMP 0x90D00A5          //比对失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETNUMBER 0x90D00A6       //获取序列号失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETEXT 0x90D00B0          //获取扩展信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETEXTACCEPT 0x90D00B1    //获取接受信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETEXTTRANS 0x90D00B2     //获取传输信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETEXTSESSION 0x90D00B3   //获取会话信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETEXTRANGE 0x90D00B4     //获取播放位置信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETEXTKEY 0x90D00B5       //获取关键帧设置失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETUSERINFO 0x90D00B6     //获取用户信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETCTX 0x90D00C0          //内容解析失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETCTXTYPE 0x90D00C1      //内容类型解析失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PARSE_PARSE_GETCTXLEN 0x90D00C2       //内容长度解析失败
/************************************************************************/
/*                            RTSP协议包帮助错误导出                    */
/************************************************************************/
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_TRANSPORT_PARAMENT 0x90D1000     //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_TRANSPORT_NOPROTO 0x90D1001      //没有协议类型
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_TRANSPORT_NOTYPE 0x90D1002       //没有传输类型
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_TRANSPORT_NOPORT 0x90D1003       //没有端口
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_RANGE_PARAMENT 0x90D1010         //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_RANGE_NOTYPE 0x90D1011           //没有传输类型
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_TRANSPORT_NORANGE 0x90D1012      //没有传输位置
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_URL_PARAMENT 0x90D1020           //解析URL失败,参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_URL_NOTHDR 0x90D1021             //没有请求头
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_HELP_URL_NOTURL 0x90D1022             //没有URL
/************************************************************************/
/*                            RTSP协议包打包函数导出错误                */
/************************************************************************/
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_OPTION_PARAMENT 0x90D2000       //选项打包函数失败,参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_GETSTATUS_PARAMENT 0x90D2010    //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_GETSTATUS_NOTSUPPORT 0x90D2011  //不支持的值
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_DESCRIBE_PARAMENT 0x90D2020     //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_SETUP_PARAMENT 0x90D2030        //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_PLAY_PARAMENT 0x90D2040         //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_PASUE_PARAMENT 0x90D2050        //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_TEARDOWN_PARAMENT 0x90D2060     //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_PARAMENT_PARAMENT 0x90D2070     //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_CODEMSG_PARAMENT 0x90D2080      //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CORE_PACKET_AUTH_PARAMENT 0x90D2090         //参数错误
//////////////////////////////////////////////////////////////////////////
///                           RTSP客户端相关错误码
//////////////////////////////////////////////////////////////////////////
/************************************************************************/
/*                            RTSP协议打包函数导出错误                  */
/************************************************************************/
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PACKET_OPTION_PARAMENT 0x90DA001    //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PACKET_DESCRIBE_PARAMENT 0x90DA010  //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PACKET_SETUP_PARAMENT 0x90DA020     //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PACKET_PLAY_PARAMENT 0x90DA030      //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PACKET_PASUE_PARAMENT 0x90DA040     //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PACKET_TEARDOWN_PARAMENT 0x90DA050  //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PACKET_PARAMENT_PARAMENT 0x90DA060  //参数错误
/************************************************************************/
/*                            RTSP协议解析函数导出错误                  */
/************************************************************************/
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_PARSEINFO_PARAMENT 0x90DA101  //参数错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_PARSEINFO_BUFFER 0x90DA102    //提供的缓冲区不正确
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_PARSEINFO_SEQERROR 0x90DA103  //SEQ错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_STATUS_GETVERSION 0x90DA110   //获取版本号信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_STATUS_NOTRTSP 0x90DA111      //不是RTSP协议
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_STATUS_GETCODE 0x90DA112      //获取服务器返回状态码失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_STATUS_GETMSG 0x90DA113       //获取状态消息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_SEQ_GETSEQ 0x90DA120          //获取SEQ信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_SEQ_NOTSEQ 0x90DA121          //不是SEQ消息,协议错误
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_SEQ_GETNUMBER 0x90DA122       //获取SEQ值失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_EXTEND_GETEXT 0x90DA130       //获取扩展信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_EXTEND_GETPUBLISH 0x90DA131   //获取可用选项失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_EXTEND_GETTRANS 0x90DA132     //获取传输信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_EXTEND_GETSESSION 0x90DA133   //获取会话信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_EXTEND_SESSIONID 0x90DA134    //获取会话ID失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_EXTEND_GETRANGE 0x90DA135     //获取传输范围失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_EXTEND_GETAUTH 0x90DA136      //获取验证信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_EXTEND_AUTHNOTS 0x90DA137     //不支持的验证模式
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_CONTEXT_GETCTX 0x90DA140      //获取附加内容失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_CONTEXT_GETCTXTYPE 0x90DA141  //获取附加类型失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_CONTEXT_GETCTXLEN 0x90DA142   //获取附加信息长度失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_TRANSPORT_FAILED 0x90DA150    //解析网络传输信息失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_TRANSPORT_NOTYPE 0x90DA151    //获取传输模式失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_TRANSPORT_ADDR 0x90DA152      //获取地址失败
#define ERROR_STREAMMEDIA_RTSPPROTOCOL_CLIENT_PARSE_TRANSPORT_PORT 0x90DA153      //获取端口失败
