copy /Y "..\XEngine_BaseLib\Bin\XEngine_BaseLib.dll" "./XEngine_Shared/XEngine_BaseLib.dll"
copy /Y "..\XEngine_BaseLib\Bin\XEngine_Algorithm.dll" "./XEngine_Shared/XEngine_Algorithm.dll"
copy /Y "..\XEngine_Core\Bin\XEngine_Core.dll" "./XEngine_Shared/XEngine_Core.dll"
copy /Y "..\XEngine_Core\Bin\XEngine_ManagePool.dll" "./XEngine_Shared/XEngine_ManagePool.dll"
copy /Y "..\XEngine_HelpComponents\Bin\HelpComponents_Packets.dll" "./XEngine_Shared/HelpComponents_Packets.dll"
copy /Y "..\XEngine_HelpComponents\Bin\HelpComponents_XLog.dll" "./XEngine_Shared/HelpComponents_XLog.dll"
copy /Y "..\XEngine_WinApi\Bin\XEngine_WinSdk.dll" "./XEngine_Shared/XEngine_WinSdk.dll"
copy /Y "..\XEngine_Client\Bin\XClient_Socket.dll" "./XEngine_Shared/XClient_Socket.dll"